import React, { useCallback, useEffect, useMemo, useState } from "react";
import { FiCalendar, FiRefreshCw, FiSearch, FiUserCheck, FiUserMinus } from "react-icons/fi";
import { toast } from "react-toastify";
import { useAuth } from "../../auth/AuthContext";
import { cancelDeparture, loadCommerceAdmin, loadStudentLifecycle, previewDeparture, processDeparture, restoreStudent, scheduleDeparture } from "../../services/commerceService";
import "./css/Commerce.scss";

const today = () => new Intl.DateTimeFormat("en-CA", { timeZone:"Asia/Taipei", year:"numeric", month:"2-digit", day:"2-digit" }).format(new Date());
const currentEnrollment = student => (student.academy_enrollments||[]).find(item=>["active","paused"].includes(item.status)) || (student.academy_enrollments||[]).sort((a,b)=>String(b.enrolled_at).localeCompare(String(a.enrolled_at)))[0] || null;
const lifecycleStatus = student => { const enrollment=currentEnrollment(student); return enrollment?.status==="active" ? enrollment.scheduled_departure_at ? "scheduled" : "active" : enrollment ? "departed" : "other"; };

function AdminStudentLifecycle(){
 const {firebaseUser}=useAuth(); const [data,setData]=useState(null);const[filter,setFilter]=useState("active");const[search,setSearch]=useState("");const[selected,setSelected]=useState(null);const[detail,setDetail]=useState(null);const[departureDate,setDepartureDate]=useState(today());const[reason,setReason]=useState("");const[preview,setPreview]=useState(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!firebaseUser)return;try{setData(await loadCommerceAdmin(firebaseUser));}catch(error){toast.error(error.message);}},[firebaseUser]);useEffect(()=>{load();},[load]);
 const students=useMemo(()=>(data?.students||[]).filter(student=>lifecycleStatus(student)===filter&&`${student.name} ${student.chinese_name||""} ${student.english_name||""} ${student.class||""}`.toLowerCase().includes(search.toLowerCase())),[data,filter,search]);
 const selectStudent=async student=>{setSelected(student);setPreview(null);setBusy(true);try{const result=await loadStudentLifecycle(firebaseUser,student.id);setDetail(result.detail);}catch(error){toast.error(error.message);}finally{setBusy(false);}};
 const doPreview=async()=>{if(!selected)return;setBusy(true);try{const result=await previewDeparture(firebaseUser,selected.id,departureDate);setPreview(result.detail);}catch(error){toast.error(error.message);}finally{setBusy(false);}};
 const act=async action=>{if(!selected)return;if(action==="schedule"&&!preview)return toast.info("請先預覽離校影響");if(!window.confirm(action==="schedule"?`確認 ${departureDate} 生效離校？已付款方案只會排程於 current_period_end 取消。`:"確認執行此狀態變更？"))return;setBusy(true);try{if(action==="schedule")await scheduleDeparture(firebaseUser,selected.id,departureDate,reason);if(action==="cancel")await cancelDeparture(firebaseUser,selected.id);if(action==="restore")await restoreStudent(firebaseUser,selected.id);if(action==="process")await processDeparture(firebaseUser,selected.id);toast.success("學生生命週期已更新");setDetail(null);setSelected(null);setPreview(null);await load();}catch(error){toast.error(error.message);}finally{setBusy(false);}};
 const planLabel=plan=>{const p=Array.isArray(plan.subscription_plans)?plan.subscription_plans[0]:plan.subscription_plans;return `${p?.name||p?.code||"方案"}：${plan.stripe_subscription_status==="past_due"?"付款失敗":plan.cancel_at_period_end?`本期 ${plan.current_period_end?.slice(0,10)||"—"} 結束取消`:plan.current_period_end?`續訂／到期 ${plan.current_period_end.slice(0,10)}`:plan.ends_at?`到期 ${plan.ends_at.slice(0,10)}`:plan.status}`;};
 return <main className="commerce-page commerce-admin"><section className="commerce-hero"><div><span>STUDENT LIFECYCLE</span><h1>在校生／離校生管理</h1><p>離校不是停用帳號。在學期間適用的教材會轉為永久教材權限，XP、AE Points、歷史作業及學習紀錄也會保留。</p></div><aside><FiUserCheck/><strong>NT$299 恢復自主學習</strong><span>離校生可使用全部正式聽力教材，不必重買以前的實體書，但不會再取得新班級作業。</span></aside></section>
 <section className="commerce-admin-panel"><div className="commerce-admin-toolbar"><label>狀態<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">在校生</option><option value="scheduled">預定離校</option><option value="departed">離校生</option></select></label><label className="is-search"><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜尋姓名或班級"/></label><strong>{students.length} 人</strong></div><table className="commerce-table"><thead><tr><th>學生</th><th>班級</th><th>狀態</th><th>入學／離校</th><th>操作</th></tr></thead><tbody>{students.map(student=>{const enrollment=currentEnrollment(student);return <tr key={student.id}><td>{student.chinese_name||student.name}<small>{student.english_name?` / ${student.english_name}`:""}</small></td><td>{student.class||"—"}</td><td><span className="commerce-status">{lifecycleStatus(student)==="active"?"在校":lifecycleStatus(student)==="scheduled"?"預定離校":"離校"}</span></td><td>{enrollment?.enrolled_at||"—"}／{enrollment?.scheduled_departure_at||enrollment?.departed_at||"—"}</td><td><button onClick={()=>selectStudent(student)}>查看方案與影響</button></td></tr>})}</tbody></table></section>
 {selected&&<section className="commerce-admin-panel"><header><FiCalendar/><h2>{selected.chinese_name||selected.name} 的方案與離校影響</h2></header>{busy&&!detail?<p>讀取中…</p>:detail&&<><div className="commerce-form"><label>離校生效日<input type="date" min={today()} value={departureDate} onChange={e=>{setDepartureDate(e.target.value);setPreview(null);}}/></label><label>原因（選填）<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div><div className="commerce-impact"><h2>權限來源</h2><p>目前班級教材：{detail.class_books?.map(book=>book?.name).filter(Boolean).join("、")||"無"}</p><p>離校後永久保留的歷史教材：{detail.historical_class_books?.map(book=>book?.book_name).filter(Boolean).join("、")||"無可回填的版本紀錄"}</p><p>已購買／兌換／贈送教材：{detail.direct_entitlements?.filter(item=>item.source!=="academy_history").map(item=>item.books?.name).filter(Boolean).join("、")||"無"}</p><p>新班級作業：離校生效後停止；歷史作業 {detail.affected_assignments?.length||0} 份保留。</p><p>基本會員／AI：{detail.plans?.map(planLabel).join("；")||"無"}</p><p>NT$299 會恢復全部正式聽力教材、會話與複習功能，不需要重買實體書；離校生仍不會取得新班級作業。</p><p>XP {detail.gamification?.total_xp||0}、AE Points {detail.gamification?.points_balance||0}、等級 {detail.level?.learning_levels?.name_zh||detail.level?.unlocked_rank||"—"} 均保留。</p></div><div className="commerce-admin-actions"><button onClick={doPreview} disabled={busy}>預覽離校</button>{lifecycleStatus(selected)==="active"&&<button className="primary" onClick={()=>act("schedule")} disabled={busy||!preview}><FiUserMinus/>預定離校</button>}{lifecycleStatus(selected)==="scheduled"&&<><button onClick={()=>act("cancel")} disabled={busy}><FiRefreshCw/>取消預定</button><button className="primary" onClick={()=>act("process")} disabled={busy}>執行到期離校</button></>}{lifecycleStatus(selected)==="departed"&&<button className="primary" onClick={()=>act("restore")} disabled={busy}><FiUserCheck/>恢復在校</button>}</div></>}</section>}
 </main>;
}
export default AdminStudentLifecycle;
