import React, { useCallback, useEffect, useState } from "react";
import { FiPackage, FiRefreshCw, FiTruck } from "react-icons/fi";
import { toast } from "react-toastify";
import { useAuth } from "../../auth/AuthContext";
import { loadAdminStoreOrders, updateStoreFulfillment, updateStoreShippingMethod } from "../../services/storeService";
import "./css/Store.scss";
import "./css/StoreAdmin.scss";

const STATUS = { awaiting_payment: "等待付款", preparing: "準備中", shipping: "運送中", completed: "已完成", cancelled: "已取消" };
const PAYMENT_STATUS = { pending: "等待付款", paid: "已付款", failed: "付款失敗", expired: "付款逾時", refunded: "已退款", cancelled: "已取消付款" };

export default function AdminStoreOrders() {
    const { firebaseUser } = useAuth(); const [orders, setOrders] = useState([]); const [methods, setMethods] = useState([]); const [busy, setBusy] = useState("");
    const load = useCallback(async () => { if (!firebaseUser) return; try { const result = await loadAdminStoreOrders(firebaseUser); setOrders(result.orders || []); setMethods(result.shipping_methods || []); } catch (error) { toast.error(error.message); } }, [firebaseUser]);
    useEffect(() => { load(); }, [load]);
    const change = (id, field, value) => setOrders(current => current.map(order => order.id === id ? { ...order, [field]: value } : order));
    const save = async order => { setBusy(String(order.id)); try { await updateStoreFulfillment(firebaseUser, { order_id: order.id, fulfillment_status: order.fulfillment_status, carrier: order.carrier, tracking_number: order.tracking_number, tracking_url: order.tracking_url }); toast.success("出貨進度已更新"); await load(); } catch (error) { toast.error(error.message); } finally { setBusy(""); } };
    const saveShipping = async method => { setBusy(`shipping-${method.code}`); try { await updateStoreShippingMethod(firebaseUser, method); toast.success("配送方式已更新"); await load(); } catch (error) { toast.error(error.message); } finally { setBusy(""); } };
    return <main className="store-admin-page"><header><div><span>STORE FULFILLMENT</span><h1>教材商城訂單與出貨</h1><p>只有 Stripe 已確認付款的訂單才能進入準備中、運送中與已完成。</p></div><button onClick={load}><FiRefreshCw />重新整理</button></header>
        <section className="store-admin-shipping"><h2>配送方式與運費</h2>{methods.map(method => <div key={method.code}><label><span>名稱</span><input value={method.name} onChange={event => setMethods(current => current.map(item => item.code === method.code ? { ...item, name: event.target.value } : item))} /></label><label><span>運費（TWD）</span><input type="number" min="0" max="10000" value={method.fee_twd} onChange={event => setMethods(current => current.map(item => item.code === method.code ? { ...item, fee_twd: Number(event.target.value) } : item))} /></label><label className="check"><input type="checkbox" checked={method.enabled} onChange={event => setMethods(current => current.map(item => item.code === method.code ? { ...item, enabled: event.target.checked } : item))} />啟用</label><button disabled={busy === `shipping-${method.code}`} onClick={() => saveShipping(method)}>{busy === `shipping-${method.code}` ? "儲存中…" : "儲存配送設定"}</button></div>)}</section>
        <section className="store-admin-orders">{orders.map(order => <article key={order.id}><header><div><strong>{order.order_number}</strong><span>{order.customer_email}</span></div><b className={order.payment_status === "cancelled" ? "is-cancelled" : ""}>{PAYMENT_STATUS[order.payment_status] || "未付款"}</b></header><div className="store-admin-order-body"><div><span>收件資料</span><strong>{order.recipient_name} · {order.recipient_phone}</strong><p>{order.postal_code} {order.city}{order.district}{order.address_line1}{order.address_line2 || ""}</p></div><div><span>商品</span>{(order.store_order_items || []).map(item => <p key={item.id}>{item.package_name} × {item.quantity}</p>)}</div></div><div className="store-admin-fulfillment"><label><span>出貨狀態</span><select disabled={order.payment_status !== "paid"} value={order.fulfillment_status} onChange={e => change(order.id, "fulfillment_status", e.target.value)}><option value="preparing">準備中</option><option value="shipping">運送中</option><option value="completed">已完成</option></select></label><label><span>物流公司</span><input disabled={order.payment_status !== "paid"} value={order.carrier || ""} onChange={e => change(order.id, "carrier", e.target.value)} /></label><label><span>物流單號</span><input disabled={order.payment_status !== "paid"} value={order.tracking_number || ""} onChange={e => change(order.id, "tracking_number", e.target.value)} /></label><label><span>物流查詢網址</span><input type="url" disabled={order.payment_status !== "paid"} value={order.tracking_url || ""} onChange={e => change(order.id, "tracking_url", e.target.value)} /></label><button disabled={order.payment_status !== "paid" || busy === String(order.id)} onClick={() => save(order)}>{order.fulfillment_status === "shipping" ? <FiTruck /> : <FiPackage />}{busy === String(order.id) ? "儲存中…" : `儲存${STATUS[order.fulfillment_status] || "狀態"}`}</button></div></article>)}</section>
    </main>;
}
