import React, { useCallback, useEffect, useState } from "react";
import { FiArchive, FiEdit3, FiPackage, FiPlus, FiUploadCloud } from "react-icons/fi";
import { toast } from "react-toastify";
import { useAuth } from "../../auth/AuthContext";
import { discontinueMaterialPackage, loadCommerceAdmin, publishMaterialPackage, saveMaterialPackage } from "../../services/commerceService";
import "./css/Commerce.scss";

const emptyForm = { name:"",level_code:"",suitable_for:"",learning_goals:"",description:"",cover_url:"",prerequisite_package_id:"",next_package_id:"",recommendation_rank:0,standard_price_twd:"",member_price_twd:"",includes_90_day_access:true,stripe_product_id:"",stripe_standard_price_id:"",stripe_member_price_id:"",workbook_id:"",listening_book_id:"",web_material_ids:[],included_audio_ids:[],sample_audio_ids:[] };
const toggle = (list, id) => list.includes(id) ? list.filter(value => value !== id) : [...list, id];

function AdminMaterialPackages() {
    const { firebaseUser } = useAuth();
    const [data, setData] = useState(null); const [form, setForm] = useState(emptyForm); const [busy,setBusy]=useState(false);
    const load = useCallback(async()=>{ if(!firebaseUser)return; try{setData(await loadCommerceAdmin(firebaseUser));}catch(error){toast.error(error.message);} },[firebaseUser]);
    useEffect(()=>{load();},[load]);
    const edit = item => { const books=item.material_package_books||[],tracks=item.material_package_tracks||[]; setForm({...emptyForm,...item,standard_price_twd:item.standard_price_twd??"",member_price_twd:item.member_price_twd??"",workbook_id:books.find(x=>x.role==="workbook")?.book_id||"",listening_book_id:books.find(x=>x.role==="listening_book")?.book_id||"",web_material_ids:books.filter(x=>x.role==="web_material").map(x=>Number(x.book_id)),included_audio_ids:tracks.filter(x=>x.role==="included_audio").map(x=>Number(x.track_id)),sample_audio_ids:tracks.filter(x=>x.role==="sample_audio").map(x=>Number(x.track_id))}); window.scrollTo({top:0,behavior:"smooth"}); };
    const payload = ()=>({...form,books:[form.workbook_id&&{book_id:Number(form.workbook_id),role:"workbook"},form.listening_book_id&&{book_id:Number(form.listening_book_id),role:"listening_book"},...form.web_material_ids.map(book_id=>({book_id,role:"web_material"}))].filter(Boolean),tracks:[...form.included_audio_ids.map(track_id=>({track_id,role:"included_audio"})),...form.sample_audio_ids.map(track_id=>({track_id,role:"sample_audio"}))]});
    const save=async event=>{event.preventDefault();setBusy(true);try{const result=await saveMaterialPackage(firebaseUser,payload());toast.success("商品包草稿已儲存");setForm(current=>({...current,id:result.package.id}));await load();}catch(error){toast.error(error.message);}finally{setBusy(false);}};
    const setStatus=async(id,action)=>{setBusy(true);try{if(action==="publish")await publishMaterialPackage(firebaseUser,id);else await discontinueMaterialPackage(firebaseUser,id);toast.success(action==="publish"?"測試模式商品包已上架":"商品包已停售");await load();}catch(error){toast.error(error.message==="material_package_incomplete"?"上架前必須有一般價、會員價、Stripe 測試 Product／兩個 Price，且各一本 Workbook 與聽力本":error.message);}finally{setBusy(false);}};
    return <main className="commerce-page commerce-admin"><section className="commerce-hero"><div><span>MATERIAL PACKAGE ADMIN</span><h1>教材商品包管理</h1><p>商品包與班級教材分開。價格或內容不完整時資料庫會阻止上架；此階段只允許 Stripe 測試模式。</p></div><aside><FiPackage/><strong>不猜正式價格</strong><span>一般售價與有效會員教材價須由管理員明確輸入。</span></aside></section>
        <section className="commerce-admin-panel"><header><FiEdit3/><h2>{form.id?"編輯商品包":"建立商品包草稿"}</h2></header><form className="commerce-form" onSubmit={save}>
            <label>商品包名稱<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>程度<input value={form.level_code} onChange={e=>setForm({...form,level_code:e.target.value})}/></label><label>適合年級或能力<input value={form.suitable_for} onChange={e=>setForm({...form,suitable_for:e.target.value})}/></label><label>推薦排序<input type="number" value={form.recommendation_rank} onChange={e=>setForm({...form,recommendation_rank:Number(e.target.value)})}/></label>
            <label className="wide">學習目標<textarea value={form.learning_goals} onChange={e=>setForm({...form,learning_goals:e.target.value})}/></label><label className="wide">商品說明<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">封面網址<input type="url" value={form.cover_url||""} onChange={e=>setForm({...form,cover_url:e.target.value})}/></label>
            <label>Workbook<select required value={form.workbook_id} onChange={e=>setForm({...form,workbook_id:e.target.value})}><option value="">請選擇</option>{(data?.books||[]).map(book=><option key={book.id} value={book.id}>{book.name}</option>)}</select></label><label>聽力本<select required value={form.listening_book_id} onChange={e=>setForm({...form,listening_book_id:e.target.value})}><option value="">請選擇</option>{(data?.books||[]).map(book=><option key={book.id} value={book.id}>{book.name}</option>)}</select></label>
            <label>前置教材<select value={form.prerequisite_package_id||""} onChange={e=>setForm({...form,prerequisite_package_id:e.target.value})}><option value="">無</option>{(data?.packages||[]).filter(x=>x.id!==form.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>下一級推薦<select value={form.next_package_id||""} onChange={e=>setForm({...form,next_package_id:e.target.value})}><option value="">無</option>{(data?.packages||[]).filter(x=>x.id!==form.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
            <label>一般售價（TWD）<input type="number" min="1" value={form.standard_price_twd} onChange={e=>setForm({...form,standard_price_twd:e.target.value})}/></label><label>有效會員教材價（TWD）<input type="number" min="1" value={form.member_price_twd} onChange={e=>setForm({...form,member_price_twd:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.includes_90_day_access} onChange={e=>setForm({...form,includes_90_day_access:e.target.checked})}/>一般購買附贈 90 天</label><span/>
            <label>Stripe 測試 Product ID<input value={form.stripe_product_id||""} onChange={e=>setForm({...form,stripe_product_id:e.target.value})} placeholder="prod_..."/></label><label>Stripe 一般價 Price ID<input value={form.stripe_standard_price_id||""} onChange={e=>setForm({...form,stripe_standard_price_id:e.target.value})} placeholder="price_..."/></label><label>Stripe 會員價 Price ID<input value={form.stripe_member_price_id||""} onChange={e=>setForm({...form,stripe_member_price_id:e.target.value})} placeholder="price_..."/></label>
            <div className="commerce-admin-actions wide"><button type="button" onClick={()=>setForm(emptyForm)}><FiPlus/>新草稿</button><button className="primary" disabled={busy}><FiEdit3/>{busy?"儲存中…":"儲存草稿"}</button></div>
        </form></section>
        <section className="commerce-admin-panel"><header><FiUploadCloud/><h2>網站教材與音檔加掛</h2></header><div className="commerce-book-groups"><section><h2>網站教材</h2><div>{(data?.books||[]).map(book=><label key={book.id}><input type="checkbox" checked={form.web_material_ids.includes(Number(book.id))} onChange={()=>setForm({...form,web_material_ids:toggle(form.web_material_ids,Number(book.id))})}/><span><strong>{book.name}</strong><small>{book.code}</small></span></label>)}</div></section><section><h2>音檔與試聽</h2><div>{(data?.tracks||[]).map(track=><label key={track.id}><input type="checkbox" checked={form.included_audio_ids.includes(Number(track.id))} onChange={()=>setForm({...form,included_audio_ids:toggle(form.included_audio_ids,Number(track.id))})}/><span><strong>{track.title||track.music_name}</strong><small>{track.preview_enabled?"可設為試聽":"完整音檔"}</small></span></label>)}</div></section><section><h2>公開試聽音檔</h2><div>{(data?.tracks||[]).filter(track=>track.preview_enabled).map(track=><label key={track.id}><input type="checkbox" checked={form.sample_audio_ids.includes(Number(track.id))} onChange={()=>setForm({...form,sample_audio_ids:toggle(form.sample_audio_ids,Number(track.id))})}/><span><strong>{track.title||track.music_name}</strong><small>短效預簽 URL</small></span></label>)}</div></section></div></section>
        <section className="commerce-admin-panel"><header><FiPackage/><h2>商品包清單</h2></header><table className="commerce-table"><thead><tr><th>名稱</th><th>程度</th><th>一般／會員價</th><th>狀態</th><th>Stripe</th><th>操作</th></tr></thead><tbody>{(data?.packages||[]).map(item=><tr key={item.id}><td>{item.name}</td><td>{item.level_code||"—"}</td><td>{item.standard_price_twd||"—"}／{item.member_price_twd||"—"}</td><td><span className="commerce-status">{item.status}</span></td><td>{item.stripe_product_id?"測試對應已填":"未完成"}</td><td><button disabled={item.status==="published"} title={item.status==="published"?"請先停售，再修改商品包":"編輯商品包"} onClick={()=>edit(item)}><FiEdit3/>{item.status==="published"?"先停售再編輯":"編輯"}</button> {item.status!=="published"&&<button className="primary" disabled={busy} onClick={()=>setStatus(item.id,"publish")}><FiUploadCloud/>上架</button>} {item.status!=="discontinued"&&<button disabled={busy} onClick={()=>setStatus(item.id,"stop")}><FiArchive/>停售</button>}</td></tr>)}</tbody></table></section>
    </main>;
}
export default AdminMaterialPackages;
