import React from "react";
import "@testing-library/jest-dom";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import useStaffPageQuery from "./useStaffPageQuery";
import { useAuth } from "../auth/AuthContext";
import { clearStaffPageCache } from "../services/staffPageCache";
jest.mock("../auth/AuthContext", () => ({ useAuth: jest.fn() }));
const loader = jest.fn();
function Page() { const query = useStaffPageQuery("accounts", loader); return <><div>{query.data?.name || "No data"}</div><span>{query.loading ? "Loading" : query.refreshing ? "Refreshing" : "Ready"}</span><span>{query.error ? "Read failed" : ""}</span><button onClick={() => query.refresh()}>Reload</button></>; }
beforeEach(() => { clearStaffPageCache(); jest.clearAllMocks(); useAuth.mockReturnValue({ firebaseUser: { uid: "staff-a" }, role: "admin" }); });
test("returning renders cached data while avoiding another fresh request", async () => { loader.mockResolvedValue({ name: "Accounts" }); const first = render(<Page />); await screen.findByText("Accounts"); first.unmount(); render(<Page />); expect(screen.getByText("Accounts")).toBeInTheDocument(); await screen.findByText("Ready"); expect(loader).toHaveBeenCalledTimes(1); });
test("an offline forced refresh retains data but a denied refresh removes it", async () => { loader.mockResolvedValue({ name: "Accounts" }); render(<Page />); await screen.findByText("Accounts"); loader.mockRejectedValueOnce(new TypeError("offline")); fireEvent.click(screen.getByText("Reload")); await screen.findByText("Read failed"); expect(screen.getByText("Accounts")).toBeInTheDocument(); loader.mockRejectedValueOnce(Object.assign(new Error("denied"), { status: 403 })); fireEvent.click(screen.getByText("Reload")); await screen.findByText("Read failed"); expect(screen.queryByText("Accounts")).not.toBeInTheDocument(); });
test("switching UID while a read is pending never renders the former account response", async () => { let finish; loader.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockResolvedValue({ name: "New staff" }); const view = render(<Page />); await waitFor(() => expect(loader).toHaveBeenCalledTimes(1)); useAuth.mockReturnValue({ firebaseUser: { uid: "staff-b" }, role: "teacher" }); view.rerender(<Page />); await screen.findByText("New staff"); await act(async () => finish({ name: "Private old staff" })); expect(screen.queryByText("Private old staff")).not.toBeInTheDocument(); });
test("a student or signed-out scope cannot start staff requests or reuse display data", async () => { useAuth.mockReturnValue({ firebaseUser: { uid: "staff-a" }, role: "student" }); render(<Page />); expect(screen.getByText("No data")).toBeInTheDocument(); fireEvent.click(screen.getByText("Reload")); await act(async () => {}); expect(loader).not.toHaveBeenCalled(); });

test("a long-open page keeps its list through a failed refresh, then expires after leaving", async () => { const clock = jest.spyOn(Date, "now"); clock.mockReturnValue(1000); loader.mockResolvedValue({ name: "Accounts" }); const view = render(<Page />); await screen.findByText("Accounts"); clock.mockReturnValue(1000 + 6 * 60 * 1000); loader.mockRejectedValueOnce(new TypeError("offline after editing")); fireEvent.click(screen.getByText("Reload")); await screen.findByText("Read failed"); expect(screen.getByText("Accounts")).toBeInTheDocument(); view.unmount(); loader.mockResolvedValueOnce({ name: "Fresh after return" }); render(<Page />); expect(screen.queryByText("Accounts")).not.toBeInTheDocument(); await screen.findByText("Fresh after return"); clock.mockRestore(); });
