import React, { useState } from "react";
import "@testing-library/jest-dom";
import { fireEvent, render, screen } from "@testing-library/react";
import { Link, MemoryRouter, Route, Routes, useNavigate } from "react-router-dom";
import useUnsavedChanges, { cancelUnsavedLeaveApproval, confirmUnsavedChanges } from "./useUnsavedChanges";
function Form({ enabled = true }) { const [value, setValue] = useState(""); const [saved, setSaved] = useState(""); const go = useNavigate(); const close = useUnsavedChanges(value !== saved, { enabled });
 return <><input aria-label="Draft" value={value} onChange={e => setValue(e.target.value)} /><button onClick={() => setSaved(value)}>Save</button><button onClick={() => close() && setValue(saved)}>Close</button><Link to="/after">Leave</Link><button onClick={() => go("/after", { replace: true })}>Replace</button></>; }
const page = props => render(<MemoryRouter initialEntries={["/form"]}><Routes><Route path="/form" element={<Form {...props} />} /><Route path="/after" element={<h1>After</h1>} /></Routes></MemoryRouter>);
beforeEach(() => jest.spyOn(window, "confirm").mockReturnValue(false)); afterEach(() => jest.restoreAllMocks());
test("clean forms leave without a prompt", () => { page(); fireEvent.click(screen.getByText("Leave")); expect(screen.getByText("After")).toBeInTheDocument(); expect(window.confirm).not.toHaveBeenCalled(); });
test.each(["Leave", "Replace"])("cancelled %s keeps the changed draft mounted", action => { page(); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); fireEvent.click(screen.getByText(action)); expect(screen.getByLabelText("Draft")).toHaveValue("Unsaved"); expect(screen.queryByText("After")).not.toBeInTheDocument(); expect(window.confirm).toHaveBeenCalledTimes(1); });
test("accepting a dirty leave proceeds once", () => { window.confirm.mockReturnValue(true); page(); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); fireEvent.click(screen.getByText("Leave")); expect(screen.getByText("After")).toBeInTheDocument(); expect(window.confirm).toHaveBeenCalledTimes(1); });
test("saving or reverting removes the prompt", () => { page(); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Saved" } }); fireEvent.click(screen.getByText("Save")); fireEvent.click(screen.getByText("Leave")); expect(window.confirm).not.toHaveBeenCalled(); });
test("native unload warns only while dirty; disabled scope allows auth redirects", () => { const view = page(); let event = new Event("beforeunload", { cancelable: true }); window.dispatchEvent(event); expect(event.defaultPrevented).toBe(false); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); event = new Event("beforeunload", { cancelable: true }); window.dispatchEvent(event); expect(event.defaultPrevented).toBe(true); view.unmount(); page({ enabled: false }); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Expired" } }); fireEvent.click(screen.getByText("Leave")); expect(screen.getByText("After")).toBeInTheDocument(); expect(window.confirm).not.toHaveBeenCalled(); });

test("explicit logout requests can be cancelled before auth data is cleared", () => { page(); expect(confirmUnsavedChanges()).toBe(true); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); expect(confirmUnsavedChanges()).toBe(false); expect(screen.getByLabelText("Draft")).toHaveValue("Unsaved"); });

test("approved logout navigation asks once and failed logout restores protection", () => { page(); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); window.confirm.mockReturnValue(true); expect(confirmUnsavedChanges()).toBe(true); fireEvent.click(screen.getByText("Leave")); expect(screen.getByText("After")).toBeInTheDocument(); expect(window.confirm).toHaveBeenCalledTimes(1); });
test("failed logout keeps the draft protected", () => { page(); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Unsaved" } }); window.confirm.mockReturnValue(true); expect(confirmUnsavedChanges()).toBe(true); cancelUnsavedLeaveApproval(); window.confirm.mockReturnValue(false); fireEvent.click(screen.getByText("Leave")); expect(screen.getByLabelText("Draft")).toHaveValue("Unsaved"); expect(window.confirm).toHaveBeenCalledTimes(2); });
