import React, { useState } from "react";
import "@testing-library/jest-dom";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { Link, Route, Routes, useNavigate } from "react-router-dom";
import GuardedBrowserRouter from "./GuardedBrowserRouter";
import useUnsavedChanges from "../hooks/useUnsavedChanges";
function Form({ enabled = true }) { const [draft, setDraft] = useState(""); const navigate = useNavigate(); useUnsavedChanges(Boolean(draft), { enabled }); return <><input aria-label="Draft" value={draft} onChange={e => setDraft(e.target.value)} /><Link to="/after">Leave</Link><button onClick={() => navigate(-1)}>Back</button></>; }
function mount(enabled = true) { return render(<GuardedBrowserRouter><Routes><Route path="/first" element={<Link to="/form">Open form</Link>} /><Route path="/form" element={<Form enabled={enabled} />} /><Route path="/after" element={<h1>After</h1>} /></Routes></GuardedBrowserRouter>); }
beforeEach(() => { window.history.replaceState(null, "", "/first"); jest.spyOn(window, "confirm").mockReturnValue(false); });
afterEach(() => jest.restoreAllMocks());
test.each(["native", "programmatic"])("cancelled %s back keeps the original mounted draft", async kind => { mount(); fireEvent.click(screen.getByText("Open form")); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Never discard" } }); if (kind === "native") act(() => window.history.back()); else fireEvent.click(screen.getByText("Back")); await waitFor(() => expect(window.confirm).toHaveBeenCalledTimes(1)); await waitFor(() => expect(window.location.pathname).toBe("/form")); expect(screen.getByLabelText("Draft")).toHaveValue("Never discard"); window.confirm.mockReturnValue(true); act(() => window.history.back()); await screen.findByText("Open form"); expect(window.location.pathname).toBe("/first"); });
test("cancelled native forward keeps a newly edited form and can then proceed", async () => { mount(); fireEvent.click(screen.getByText("Open form")); fireEvent.click(screen.getByText("Leave")); expect(window.confirm).not.toHaveBeenCalled(); act(() => window.history.back()); await screen.findByLabelText("Draft"); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Keep forward draft" } }); act(() => window.history.forward()); await waitFor(() => expect(window.confirm).toHaveBeenCalledTimes(1)); await waitFor(() => expect(window.location.pathname).toBe("/form")); expect(screen.getByLabelText("Draft")).toHaveValue("Keep forward draft"); window.confirm.mockReturnValue(true); act(() => window.history.forward()); await screen.findByText("After"); expect(window.confirm).toHaveBeenCalledTimes(2); });
test("disabled auth scope permits a back redirect without prompting", async () => { mount(false); fireEvent.click(screen.getByText("Open form")); fireEvent.change(screen.getByLabelText("Draft"), { target: { value: "Expired" } }); act(() => window.history.back()); await screen.findByText("Open form"); expect(window.confirm).not.toHaveBeenCalled(); });
