// Executes the real academy recovery migration in isolated, in-memory PostgreSQL.
// It never reads credentials or connects to Supabase.
import { after, before, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const { PGlite } = await import(process.env.PGLITE_MODULE
    ? pathToFileURL(process.env.PGLITE_MODULE).href
    : "@electric-sql/pglite");
const db = new PGlite();
const migration = readFileSync(
    new URL("../supabase/migrations/20260909090000_secure_academy_recovery_codes.sql", import.meta.url),
    "utf8"
);
const scalar = async (sql, params = []) => (await db.query(sql, params)).rows[0];
const reserve = async (username, codeHash, reservationHash) => (
    await scalar("select public.reserve_academy_student_recovery_code($1, $2, $3) result", [
        username, codeHash, reservationHash
    ])
).result;

const validCodeHash = "a".repeat(64);
const otherCodeHash = "b".repeat(64);
const reservationHash = "c".repeat(64);

before(async () => {
    await db.exec(`
        create role anon;
        create role authenticated;
        create role service_role;

        create table public.students (
            id bigint primary key,
            firebase_uid text not null,
            login_username text not null,
            authentication_method text not null,
            account_status text not null
        );
        create table public.academy_student_recovery_codes (
            id bigint generated by default as identity primary key,
            student_id bigint not null references public.students(id) on delete cascade,
            code_hash char(64) not null,
            used_at timestamptz,
            revoked_at timestamptz
        );

        insert into public.students values
            (1, 'firebase-one', 'studentone', 'academy_username', 'active'),
            (2, 'firebase-two', 'studenttwo', 'academy_username', 'active');
        insert into public.academy_student_recovery_codes(student_id, code_hash)
        values (1, '${validCodeHash}'), (2, '${validCodeHash}');
    `);
    await db.exec(migration);
});

after(() => db.close());

test("同一帳號一小時五次失敗後會被限制", async () => {
    for (let attempt = 1; attempt <= 5; attempt += 1) {
        const result = await reserve("studentone", otherCodeHash, reservationHash);
        assert.equal(result.status, "invalid");
    }
    const limited = await reserve("studentone", otherCodeHash, reservationHash);
    assert.equal(limited.status, "rate_limited");
    assert.equal((await scalar(`select count(*)::int count from public.academy_student_recovery_attempts where student_id = 1 and outcome = 'failed'`)).count, 5);
});

test("有效復原碼先保留再原子消耗，不能重複使用", async () => {
    const reserved = await reserve("studenttwo", validCodeHash, reservationHash);
    assert.equal(reserved.status, "reserved");
    assert.equal(reserved.student_id, 2);

    const completed = await scalar(
        "select public.complete_academy_student_recovery_code($1, $2) completed",
        [reserved.code_id, reservationHash]
    );
    assert.equal(completed.completed, true);

    const repeated = await scalar(
        "select public.complete_academy_student_recovery_code($1, $2) completed",
        [reserved.code_id, reservationHash]
    );
    assert.equal(repeated.completed, false);
    assert.equal((await scalar(`select count(*)::int count from public.academy_student_recovery_attempts where student_id = 2 and outcome = 'succeeded'`)).count, 1);
});

test("復原嘗試表與 RPC 不開放給瀏覽器角色", async () => {
    assert.equal((await scalar("select has_table_privilege('anon', 'public.academy_student_recovery_attempts', 'select') allowed")).allowed, false);
    assert.equal((await scalar("select has_table_privilege('authenticated', 'public.academy_student_recovery_attempts', 'insert') allowed")).allowed, false);
    assert.equal((await scalar("select has_function_privilege('anon', 'public.reserve_academy_student_recovery_code(text, character, character)', 'execute') allowed")).allowed, false);
    assert.equal((await scalar("select has_function_privilege('service_role', 'public.reserve_academy_student_recovery_code(text, character, character)', 'execute') allowed")).allowed, true);
});
