// Executes the real question-count migration in an isolated, in-memory
// PostgreSQL instance. It never reads credentials or connects to Supabase.
import { after, before, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const { PGlite } = await import(process.env.PGLITE_MODULE
    ? pathToFileURL(process.env.PGLITE_MODULE).href
    : "@electric-sql/pglite");
const db = new PGlite();
const migration = readFileSync(
    new URL("../supabase/migrations/20260922012056_allow_30_speaking_generation_questions.sql", import.meta.url),
    "utf8"
);

before(async () => {
    await db.exec(`
        create table public.speaking_generation_jobs (
            id bigint generated by default as identity primary key,
            requested_count integer not null,
            constraint speaking_generation_jobs_count_check
                check (requested_count between 1 and 20)
        );
        insert into public.speaking_generation_jobs(requested_count) values (20);
    `);
    await db.exec(migration);
});

after(() => db.close());

test("migration preserves existing jobs and accepts the 30-question AI ceiling", async () => {
    await db.exec("insert into public.speaking_generation_jobs(requested_count) values (30)");
    const result = await db.query("select requested_count from public.speaking_generation_jobs order by id");
    assert.deepEqual(result.rows.map(row => row.requested_count), [20, 30]);
});

test("migration still rejects counts outside the supported range", async () => {
    await assert.rejects(
        db.exec("insert into public.speaking_generation_jobs(requested_count) values (31)"),
        /speaking_generation_jobs_count_check/
    );
});
