-- Six-digit recovery codes are intentionally rate-limited per academy account.
-- These functions are only callable by the service role through the Edge Function.

create table if not exists public.academy_student_recovery_attempts (
    id bigint generated by default as identity primary key,
    student_id bigint references public.students(id) on delete cascade,
    attempted_at timestamptz not null default now(),
    outcome text not null check (outcome in ('failed', 'succeeded'))
);

create index if not exists academy_recovery_attempts_student_recent_idx
    on public.academy_student_recovery_attempts(student_id, attempted_at desc);

alter table public.academy_student_recovery_codes
    add column if not exists reservation_hash char(64),
    add column if not exists reservation_expires_at timestamptz;

alter table public.academy_student_recovery_attempts enable row level security;
revoke all on public.academy_student_recovery_attempts from public, anon, authenticated;
revoke all on sequence public.academy_student_recovery_attempts_id_seq from public, anon, authenticated;
grant select, insert on public.academy_student_recovery_attempts to service_role;
grant usage, select on sequence public.academy_student_recovery_attempts_id_seq to service_role;

create or replace function public.reserve_academy_student_recovery_code(
    p_username text,
    p_code_hash char(64),
    p_reservation_hash char(64)
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_student public.students%rowtype;
    v_code_id bigint;
    v_failed_attempts integer;
begin
    select * into v_student
    from public.students
    where lower(btrim(login_username)) = lower(btrim(coalesce(p_username, '')))
      and authentication_method = 'academy_username'
      and account_status = 'active'
    for update;

    if not found then
        return jsonb_build_object('status', 'invalid');
    end if;

    select count(*)::integer into v_failed_attempts
    from public.academy_student_recovery_attempts
    where student_id = v_student.id
      and outcome = 'failed'
      and attempted_at >= now() - interval '1 hour';

    if v_failed_attempts >= 5 then
        return jsonb_build_object('status', 'rate_limited');
    end if;

    select id into v_code_id
    from public.academy_student_recovery_codes
    where student_id = v_student.id
      and code_hash = p_code_hash
      and used_at is null
      and revoked_at is null
      and (reservation_expires_at is null or reservation_expires_at <= now())
    for update;

    if not found then
        insert into public.academy_student_recovery_attempts (student_id, outcome)
        values (v_student.id, 'failed');
        return jsonb_build_object('status', 'invalid');
    end if;

    update public.academy_student_recovery_codes
    set reservation_hash = p_reservation_hash,
        reservation_expires_at = now() + interval '5 minutes'
    where id = v_code_id
      and used_at is null
      and revoked_at is null
      and (reservation_expires_at is null or reservation_expires_at <= now());

    if not found then
        insert into public.academy_student_recovery_attempts (student_id, outcome)
        values (v_student.id, 'failed');
        return jsonb_build_object('status', 'invalid');
    end if;

    return jsonb_build_object(
        'status', 'reserved',
        'student_id', v_student.id,
        'firebase_uid', v_student.firebase_uid,
        'username', v_student.login_username,
        'code_id', v_code_id,
        'reservation_hash', p_reservation_hash
    );
end;
$$;

create or replace function public.complete_academy_student_recovery_code(
    p_code_id bigint,
    p_reservation_hash char(64)
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_student_id bigint;
begin
    update public.academy_student_recovery_codes
    set used_at = now(),
        reservation_hash = null,
        reservation_expires_at = null
    where id = p_code_id
      and used_at is null
      and revoked_at is null
      and reservation_hash = p_reservation_hash
      and reservation_expires_at > now()
    returning student_id into v_student_id;

    if not found then
        return false;
    end if;

    insert into public.academy_student_recovery_attempts (student_id, outcome)
    values (v_student_id, 'succeeded');

    return true;
end;
$$;

revoke all on function public.reserve_academy_student_recovery_code(text, char(64), char(64)) from public, anon, authenticated;
revoke all on function public.complete_academy_student_recovery_code(bigint, char(64)) from public, anon, authenticated;
grant execute on function public.reserve_academy_student_recovery_code(text, char(64), char(64)) to service_role;
grant execute on function public.complete_academy_student_recovery_code(bigint, char(64)) to service_role;
