create table if not exists public.academy_student_import_batches (
    id bigint generated by default as identity primary key,
    request_id uuid not null unique,
    created_by bigint not null references public.students(id) on delete restrict,
    status text not null default 'processing'
        check (status in ('processing', 'completed', 'completed_with_errors', 'failed')),
    total_rows smallint not null
        check (total_rows between 1 and 25),
    success_count smallint not null default 0
        check (success_count >= 0),
    failure_count smallint not null default 0
        check (failure_count >= 0),
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint academy_student_import_batches_count_check
        check (success_count + failure_count <= total_rows)
);

create table if not exists public.academy_student_import_results (
    id bigint generated by default as identity primary key,
    batch_id bigint not null
        references public.academy_student_import_batches(id) on delete cascade,
    row_number smallint not null check (row_number > 0),
    login_email text not null,
    student_id bigint references public.students(id) on delete set null,
    status text not null check (status in ('success', 'failed')),
    error_code text,
    error_message text,
    created_at timestamptz not null default now(),
    unique (batch_id, row_number)
);

create index if not exists academy_student_import_batches_created_by_created_at_idx
    on public.academy_student_import_batches(created_by, created_at desc);

create index if not exists academy_student_import_results_batch_id_idx
    on public.academy_student_import_results(batch_id);

create index if not exists academy_student_import_results_student_id_idx
    on public.academy_student_import_results(student_id)
    where student_id is not null;

alter table public.academy_student_import_batches enable row level security;
alter table public.academy_student_import_results enable row level security;

revoke all on table public.academy_student_import_batches
    from public, anon, authenticated;
revoke all on table public.academy_student_import_results
    from public, anon, authenticated;
revoke all on sequence public.academy_student_import_batches_id_seq
    from public, anon, authenticated;
revoke all on sequence public.academy_student_import_results_id_seq
    from public, anon, authenticated;

grant select, insert, update on table public.academy_student_import_batches
    to service_role;
grant select, insert on table public.academy_student_import_results
    to service_role;
grant usage, select on sequence public.academy_student_import_batches_id_seq
    to service_role;
grant usage, select on sequence public.academy_student_import_results_id_seq
    to service_role;

comment on table public.academy_student_import_batches is
    'Server-only audit and idempotency records for admin CSV academy-student imports.';
comment on table public.academy_student_import_results is
    'Per-row CSV import outcomes. Temporary passwords are intentionally never stored.';
