create table if not exists public.links (
    id bigint generated by default as identity primary key,
    firebase_key text unique,
    title text not null,
    url text not null,
    category text not null default 'special',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    source text not null default 'manual',
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint links_title_length_check check (char_length(btrim(title)) between 1 and 120),
    constraint links_url_check check (url ~* '^https?://'),
    constraint links_category_check check (
        category in ('special', 'exercise', 'listening', 'discovery', 'speedphonics')
    ),
    constraint links_source_check check (source in ('manual', 'firebase_import')),
    constraint links_sort_order_check check (sort_order between -100000 and 100000)
);

create index if not exists links_public_order_idx
    on public.links (is_active, category, sort_order, title);

alter table public.links enable row level security;

revoke all on table public.links from anon, authenticated;
grant select on table public.links to anon, authenticated;

drop policy if exists "public can read active links" on public.links;
create policy "public can read active links"
    on public.links
    for select
    to anon, authenticated
    using (is_active = true);
