-- Web Push is opt-in per browser installation. Inbox entries remain the source of truth.
create table public.student_push_subscriptions (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    endpoint text not null unique check (char_length(endpoint) between 30 and 2048),
    p256dh text not null check (char_length(p256dh) between 40 and 200),
    auth_secret text not null check (char_length(auth_secret) between 16 and 100),
    device_label text not null default '此裝置' check (char_length(device_label) <= 80),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    disabled_at timestamptz
);
create index student_push_subscriptions_student_idx
    on public.student_push_subscriptions(student_id, active);
alter table public.student_push_subscriptions enable row level security;
revoke all on public.student_push_subscriptions from anon, authenticated;
grant all on public.student_push_subscriptions to service_role;

create table public.student_push_delivery_queue (
    id bigint generated by default as identity primary key,
    student_notification_id bigint not null references public.student_notifications(id) on delete cascade,
    subscription_id bigint not null references public.student_push_subscriptions(id) on delete cascade,
    status text not null default 'pending' check (status in ('pending','sending','sent','failed','skipped')),
    attempt_count integer not null default 0 check (attempt_count between 0 and 5),
    next_attempt_at timestamptz not null default now(),
    claimed_at timestamptz,
    last_http_status integer,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    unique (student_notification_id, subscription_id)
);
create index student_push_delivery_due_idx
    on public.student_push_delivery_queue(next_attempt_at, id)
    where status in ('pending','failed','sending');
create index student_push_delivery_daily_idx
    on public.student_push_delivery_queue(subscription_id, sent_at)
    where status = 'sent';
alter table public.student_push_delivery_queue enable row level security;
revoke all on public.student_push_delivery_queue from anon, authenticated;
grant all on public.student_push_delivery_queue to service_role;

create function public.enqueue_student_web_push() returns trigger
language plpgsql security invoker set search_path = public, pg_temp as $$
begin
    if new.notification_type = 'assignment'
        or (new.notification_type = 'membership' and new.metadata->>'event_type' = 'material_access_expiring') then
        insert into public.student_push_delivery_queue(student_notification_id, subscription_id)
        select new.id, s.id from public.student_push_subscriptions s
        where s.student_id = new.student_id and s.active = true
        on conflict (student_notification_id, subscription_id) do nothing;
    end if;
    return new;
end;
$$;
revoke all on function public.enqueue_student_web_push() from public, anon, authenticated;
grant execute on function public.enqueue_student_web_push() to service_role;
create trigger student_notifications_enqueue_web_push
after insert on public.student_notifications
for each row execute function public.enqueue_student_web_push();

-- Called only after all items of a newly published assignment were saved.
alter table public.assignments
    add column web_push_notification_ready_at timestamptz,
    add column web_push_notification_processed_at timestamptz;
create index assignments_web_push_pending_idx on public.assignments(assigned_date, id)
    where web_push_notification_ready_at is not null and web_push_notification_processed_at is null;

create function public.create_assignment_student_notifications(p_assignment_id bigint) returns integer
language plpgsql security invoker set search_path = public, pg_temp as $$
declare v_count integer;
begin
    update public.assignments set web_push_notification_ready_at = coalesce(web_push_notification_ready_at, now())
    where id = p_assignment_id and enabled = true;
    if not found then return 0; end if;

    insert into public.student_notifications(student_id, notification_type, event_key, title, body, metadata)
    select distinct e.student_id, 'assignment', 'assignment:' || a.id || ':published',
        '有新的班級作業', '老師發布了一份新作業，請登入查看。',
        jsonb_build_object('assignment_id', a.id, 'target_path', '/student/assignments', 'due_at', a.due_at)
    from public.assignments a
    join public.academy_classes c on c.code = a.target_class
    join public.academy_enrollments e on e.class_id = c.id and e.status = 'active'
    join public.students s on s.id = e.student_id and s.role = 'student' and s.account_status = 'active'
    where a.id = p_assignment_id and a.enabled = true
      and a.assigned_date <= (now() at time zone 'Asia/Taipei')::date
      and (a.due_at is null or a.due_at > now())
      and (e.scheduled_departure_at is null or e.scheduled_departure_at > (now() at time zone 'Asia/Taipei')::date)
    on conflict (student_id, event_key) where event_key is not null do nothing;
    get diagnostics v_count = row_count;
    update public.assignments set web_push_notification_processed_at = now()
    where id = p_assignment_id and assigned_date <= (now() at time zone 'Asia/Taipei')::date;
    return v_count;
end;
$$;
revoke all on function public.create_assignment_student_notifications(bigint) from public, anon, authenticated;
grant execute on function public.create_assignment_student_notifications(bigint) to service_role;

create function public.create_due_assignment_student_notifications() returns integer
language plpgsql security invoker set search_path = public, pg_temp as $$
declare assignment_row record; v_total integer := 0;
begin
    for assignment_row in
        select id from public.assignments
        where web_push_notification_ready_at is not null
          and web_push_notification_processed_at is null and enabled = true
          and assigned_date <= (now() at time zone 'Asia/Taipei')::date
        order by assigned_date, id limit 100
    loop
        v_total := v_total + public.create_assignment_student_notifications(assignment_row.id);
    end loop;
    return v_total;
end;
$$;
revoke all on function public.create_due_assignment_student_notifications() from public, anon, authenticated;
grant execute on function public.create_due_assignment_student_notifications() to service_role;

-- SKIP LOCKED prevents overlapping cron calls from claiming the same push.
create function public.claim_student_web_push(p_limit integer default 20)
returns setof public.student_push_delivery_queue
language plpgsql security invoker set search_path = public, pg_temp as $$
begin
    return query
    with due as (
        select q.id from public.student_push_delivery_queue q
        where q.attempt_count < 5 and q.next_attempt_at <= now()
          and (q.status in ('pending','failed') or (q.status = 'sending' and q.claimed_at < now() - interval '10 minutes'))
        order by q.next_attempt_at, q.id
        for update skip locked limit least(greatest(p_limit, 1), 50)
    )
    update public.student_push_delivery_queue q
    set status = 'sending', attempt_count = q.attempt_count + 1, claimed_at = now()
    from due where q.id = due.id returning q.*;
end;
$$;
revoke all on function public.claim_student_web_push(integer) from public, anon, authenticated;
grant execute on function public.claim_student_web_push(integer) to service_role;
