begin;

create table if not exists public.student_social_profiles (
    student_id bigint primary key references public.students(id) on delete cascade,
    nickname text not null,
    nickname_normalized text generated always as (lower(btrim(nickname))) stored,
    friend_code text not null,
    stats_visibility text not null default 'friends'
        check (stats_visibility in ('self', 'friends')),
    presence_visibility text not null default 'friends'
        check (presence_visibility in ('hidden', 'friends')),
    last_active_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (char_length(btrim(nickname)) between 2 and 20),
    check (friend_code ~ '^AE-[A-Z2-9]{8}$')
);

create unique index if not exists student_social_profiles_nickname_key
    on public.student_social_profiles(nickname_normalized);
create unique index if not exists student_social_profiles_friend_code_key
    on public.student_social_profiles(friend_code);
create index if not exists idx_student_social_profiles_presence
    on public.student_social_profiles(last_active_at desc);

create table if not exists public.student_friendships (
    id bigint generated by default as identity primary key,
    requester_id bigint not null references public.students(id) on delete cascade,
    addressee_id bigint not null references public.students(id) on delete cascade,
    status text not null default 'pending'
        check (status in ('pending', 'accepted', 'rejected')),
    responded_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (requester_id <> addressee_id)
);

create unique index if not exists student_friendships_pair_key
    on public.student_friendships(least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists idx_student_friendships_requester
    on public.student_friendships(requester_id, status, updated_at desc);
create index if not exists idx_student_friendships_addressee
    on public.student_friendships(addressee_id, status, updated_at desc);

create table if not exists public.student_social_blocks (
    blocker_id bigint not null references public.students(id) on delete cascade,
    blocked_id bigint not null references public.students(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (blocker_id, blocked_id),
    check (blocker_id <> blocked_id)
);

create index if not exists idx_student_social_blocks_blocked
    on public.student_social_blocks(blocked_id, blocker_id);

create table if not exists public.student_social_reports (
    id bigint generated by default as identity primary key,
    reporter_id bigint not null references public.students(id) on delete cascade,
    reported_id bigint not null references public.students(id) on delete cascade,
    category text not null
        check (category in ('inappropriate_nickname', 'harassment', 'cheating', 'other')),
    details text,
    status text not null default 'open'
        check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
    reviewed_by bigint references public.students(id) on delete set null,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    check (reporter_id <> reported_id),
    check (details is null or char_length(details) <= 500)
);

create index if not exists idx_student_social_reports_review
    on public.student_social_reports(status, created_at desc);
create index if not exists idx_student_social_reports_reporter
    on public.student_social_reports(reporter_id, created_at desc);

create table if not exists public.student_social_audit_events (
    id bigint generated by default as identity primary key,
    actor_id bigint not null references public.students(id) on delete cascade,
    target_id bigint references public.students(id) on delete set null,
    action text not null check (char_length(action) between 2 and 60),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_student_social_audit_actor_action
    on public.student_social_audit_events(actor_id, action, created_at desc);

alter table public.student_social_profiles enable row level security;
alter table public.student_friendships enable row level security;
alter table public.student_social_blocks enable row level security;
alter table public.student_social_reports enable row level security;
alter table public.student_social_audit_events enable row level security;

revoke all on table public.student_social_profiles from anon, authenticated;
revoke all on table public.student_friendships from anon, authenticated;
revoke all on table public.student_social_blocks from anon, authenticated;
revoke all on table public.student_social_reports from anon, authenticated;
revoke all on table public.student_social_audit_events from anon, authenticated;

grant all on table public.student_social_profiles to service_role;
grant all on table public.student_friendships to service_role;
grant all on table public.student_social_blocks to service_role;
grant all on table public.student_social_reports to service_role;
grant all on table public.student_social_audit_events to service_role;

alter table public.student_notifications
    drop constraint if exists student_notifications_notification_type_check;
alter table public.student_notifications
    add constraint student_notifications_notification_type_check
    check (notification_type in ('system', 'assignment', 'reward', 'birthday', 'membership', 'social'));

comment on table public.student_social_profiles is
    'Public-safe student identity served only through Firebase-verified Edge Functions.';
comment on table public.student_friendships is
    'Mutual student friendship requests. One canonical row exists per student pair.';
comment on table public.student_social_blocks is
    'Directional safety block. Blocking also removes the existing friendship through the Edge Function.';
comment on table public.student_social_reports is
    'Student safety reports for administrator review. Never exposed directly to clients.';

commit;
