begin;

create table if not exists public.student_nickname_history (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    previous_nickname text,
    new_nickname text not null,
    changed_by bigint references public.students(id) on delete set null,
    change_source text not null
        check (change_source in ('student_settings', 'friends_profile')),
    changed_at timestamptz not null default now(),
    check (previous_nickname is null or char_length(btrim(previous_nickname)) between 2 and 20),
    check (char_length(btrim(new_nickname)) between 2 and 20)
);

create index if not exists idx_student_nickname_history_student_changed
    on public.student_nickname_history(student_id, changed_at desc, id desc);

alter table public.student_nickname_history enable row level security;

revoke all on table public.student_nickname_history from public, anon, authenticated;
revoke all on sequence public.student_nickname_history_id_seq from public, anon, authenticated;
grant all on table public.student_nickname_history to service_role;
grant usage, select on sequence public.student_nickname_history_id_seq to service_role;

create or replace function public.set_student_social_profile_v1(
    p_student_id bigint,
    p_nickname text,
    p_friend_code text,
    p_stats_visibility text,
    p_presence_visibility text,
    p_changed_by bigint,
    p_change_source text
)
returns public.student_social_profiles
language plpgsql
security invoker
set search_path = ''
as $$
declare
    previous_nickname_value text;
    saved_profile public.student_social_profiles;
begin
    if p_student_id is null or p_changed_by is distinct from p_student_id then
        raise exception 'nickname_actor_mismatch';
    end if;
    if p_change_source not in ('student_settings', 'friends_profile') then
        raise exception 'nickname_change_source_invalid';
    end if;

    perform pg_catalog.pg_advisory_xact_lock(p_student_id);

    select profile.nickname
      into previous_nickname_value
      from public.student_social_profiles as profile
     where profile.student_id = p_student_id
     for update;

    insert into public.student_social_profiles (
        student_id,
        nickname,
        friend_code,
        stats_visibility,
        presence_visibility,
        last_active_at,
        updated_at
    ) values (
        p_student_id,
        p_nickname,
        p_friend_code,
        p_stats_visibility,
        p_presence_visibility,
        now(),
        now()
    )
    on conflict (student_id) do update set
        nickname = excluded.nickname,
        stats_visibility = excluded.stats_visibility,
        presence_visibility = excluded.presence_visibility,
        last_active_at = excluded.last_active_at,
        updated_at = excluded.updated_at
    returning * into saved_profile;

    if previous_nickname_value is distinct from saved_profile.nickname then
        insert into public.student_nickname_history (
            student_id,
            previous_nickname,
            new_nickname,
            changed_by,
            change_source
        ) values (
            p_student_id,
            previous_nickname_value,
            saved_profile.nickname,
            p_changed_by,
            p_change_source
        );
    end if;

    return saved_profile;
end;
$$;

revoke all on function public.set_student_social_profile_v1(bigint, text, text, text, text, bigint, text)
    from public, anon, authenticated;
grant execute on function public.set_student_social_profile_v1(bigint, text, text, text, text, bigint, text)
    to service_role;

comment on table public.student_nickname_history is
    'Server-only nickname changes visible only to the owning student and administrators through verified Edge Functions.';
comment on function public.set_student_social_profile_v1(bigint, text, text, text, text, bigint, text) is
    'Atomically updates a student social profile and records real nickname changes.';

commit;
