begin;

-- =========================================================
-- Alan English - Phase 03A
-- Annual academy placement cycles and class movement history
-- =========================================================
--
-- The official class catalog remains fixed at E1, E3, E5 and E7.
-- A placement cycle stores one reviewed decision per current academy
-- student. Applying an approved cycle updates the current enrollment
-- and writes an immutable movement history row.
--
-- This migration does not move any existing student automatically.
-- Only an approved cycle whose effective date has arrived can be applied.

-- 1. Placement cycle header.

create table if not exists public.academy_placement_cycles (
    id bigint generated by default as identity primary key,
    name text not null,
    effective_on date not null,
    status text not null default 'draft',
    notes text,
    created_by bigint not null
        references public.students(id)
        on delete restrict,
    approved_by bigint
        references public.students(id)
        on delete set null,
    approved_at timestamptz,
    applied_by bigint
        references public.students(id)
        on delete set null,
    applied_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint academy_placement_cycles_name_not_blank_check
        check (btrim(name) <> ''),
    constraint academy_placement_cycles_status_check
        check (status in ('draft', 'approved', 'applied', 'cancelled')),
    constraint academy_placement_cycles_notes_length_check
        check (notes is null or char_length(notes) <= 2000),
    constraint academy_placement_cycles_approval_state_check
        check (
            (status = 'draft' and approved_at is null and applied_at is null)
            or (status = 'cancelled' and applied_at is null)
            or (status = 'approved' and approved_at is not null and applied_at is null)
            or (status = 'applied' and approved_at is not null and applied_at is not null)
        )
);

comment on table public.academy_placement_cycles is
    'Admin-reviewed annual placement batches for E1, E3, E5 and E7 academy students.';

create index if not exists academy_placement_cycles_status_effective_idx
    on public.academy_placement_cycles (status, effective_on, id);

drop trigger if exists academy_placement_cycles_set_updated_at
    on public.academy_placement_cycles;

create trigger academy_placement_cycles_set_updated_at
before update on public.academy_placement_cycles
for each row
execute function public.set_updated_at_now();

-- 2. One placement decision per student in each cycle.

create table if not exists public.academy_placement_decisions (
    id bigint generated by default as identity primary key,
    cycle_id bigint not null
        references public.academy_placement_cycles(id)
        on delete cascade,
    student_id bigint not null
        references public.students(id)
        on delete cascade,
    enrollment_id bigint not null
        references public.academy_enrollments(id)
        on delete restrict,
    from_class_id smallint not null
        references public.academy_classes(id)
        on delete restrict,
    to_class_id smallint
        references public.academy_classes(id)
        on delete restrict,
    decision text not null default 'stay',
    reason text,
    decided_by bigint
        references public.students(id)
        on delete set null,
    decided_at timestamptz not null default now(),
    applied_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint academy_placement_decisions_decision_check
        check (decision in ('promote', 'stay', 'demote', 'graduate')),
    constraint academy_placement_decisions_target_check
        check (
            (decision = 'graduate' and to_class_id is null)
            or (decision <> 'graduate' and to_class_id is not null)
        ),
    constraint academy_placement_decisions_reason_length_check
        check (reason is null or char_length(reason) <= 2000),
    constraint academy_placement_decisions_cycle_student_key
        unique (cycle_id, student_id)
);

comment on table public.academy_placement_decisions is
    'Reviewed promote, stay, demote or graduate decision for each student in a placement cycle.';

create index if not exists academy_placement_decisions_student_history_idx
    on public.academy_placement_decisions (student_id, cycle_id desc);

create index if not exists academy_placement_decisions_cycle_apply_idx
    on public.academy_placement_decisions (cycle_id, applied_at, id);

drop trigger if exists academy_placement_decisions_set_updated_at
    on public.academy_placement_decisions;

create trigger academy_placement_decisions_set_updated_at
before update on public.academy_placement_decisions
for each row
execute function public.set_updated_at_now();

-- Validate the only allowed one-step movements between fixed classes.
create or replace function public.validate_academy_placement_decision()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    from_code text;
    to_code text;
begin
    select code
    into from_code
    from public.academy_classes
    where id = new.from_class_id
      and is_active = true;

    if from_code is null then
        raise exception 'placement_from_class_not_active';
    end if;

    if new.to_class_id is not null then
        select code
        into to_code
        from public.academy_classes
        where id = new.to_class_id
          and is_active = true;

        if to_code is null then
            raise exception 'placement_to_class_not_active';
        end if;
    end if;

    if new.decision = 'stay' and to_code is distinct from from_code then
        raise exception 'placement_stay_must_keep_class';
    elsif new.decision = 'promote'
          and (from_code, to_code) not in (('E1', 'E3'), ('E3', 'E5'), ('E5', 'E7')) then
        raise exception 'placement_invalid_promotion';
    elsif new.decision = 'demote'
          and (from_code, to_code) not in (('E7', 'E5'), ('E5', 'E3'), ('E3', 'E1')) then
        raise exception 'placement_invalid_demotion';
    elsif new.decision = 'graduate'
          and (from_code <> 'E7' or new.to_class_id is not null) then
        raise exception 'placement_only_e7_can_graduate';
    end if;

    return new;
end;
$$;

revoke all on function public.validate_academy_placement_decision()
    from public, anon, authenticated;

grant execute on function public.validate_academy_placement_decision()
    to service_role;

drop trigger if exists academy_placement_decisions_validate
    on public.academy_placement_decisions;

create trigger academy_placement_decisions_validate
before insert or update of from_class_id, to_class_id, decision
on public.academy_placement_decisions
for each row
execute function public.validate_academy_placement_decision();

-- 3. Immutable audit history for every applied decision.

create table if not exists public.academy_class_movement_history (
    id bigint generated by default as identity primary key,
    cycle_id bigint not null
        references public.academy_placement_cycles(id)
        on delete restrict,
    decision_id bigint not null
        references public.academy_placement_decisions(id)
        on delete restrict,
    student_id bigint not null
        references public.students(id)
        on delete cascade,
    enrollment_id bigint not null
        references public.academy_enrollments(id)
        on delete restrict,
    from_class_id smallint not null
        references public.academy_classes(id)
        on delete restrict,
    to_class_id smallint
        references public.academy_classes(id)
        on delete restrict,
    decision text not null,
    reason text,
    effective_on date not null,
    changed_by bigint
        references public.students(id)
        on delete set null,
    created_at timestamptz not null default now(),
    constraint academy_class_movement_history_decision_check
        check (decision in ('promote', 'stay', 'demote', 'graduate')),
    constraint academy_class_movement_history_cycle_student_key
        unique (cycle_id, student_id),
    constraint academy_class_movement_history_decision_key
        unique (decision_id)
);

comment on table public.academy_class_movement_history is
    'Immutable audit trail of applied academy placement decisions.';

create index if not exists academy_class_movement_history_student_idx
    on public.academy_class_movement_history (student_id, effective_on desc, id desc);

create index if not exists academy_class_movement_history_cycle_idx
    on public.academy_class_movement_history (cycle_id, id);

-- 4. Create a draft cycle and default every current student to stay.

create or replace function public.create_academy_placement_cycle(
    p_name text,
    p_effective_on date,
    p_created_by bigint,
    p_notes text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    new_cycle_id bigint;
    inserted_decision_count integer;
begin
    if nullif(btrim(p_name), '') is null then
        raise exception 'placement_cycle_name_required';
    end if;

    if p_effective_on is null then
        raise exception 'placement_cycle_effective_date_required';
    end if;

    if not exists (
        select 1
        from public.students
        where id = p_created_by
          and role = 'admin'
    ) then
        raise exception 'placement_cycle_admin_required';
    end if;

    insert into public.academy_placement_cycles (
        name,
        effective_on,
        status,
        notes,
        created_by
    )
    values (
        btrim(p_name),
        p_effective_on,
        'draft',
        nullif(btrim(p_notes), ''),
        p_created_by
    )
    returning id into new_cycle_id;

    insert into public.academy_placement_decisions (
        cycle_id,
        student_id,
        enrollment_id,
        from_class_id,
        to_class_id,
        decision,
        decided_by,
        decided_at
    )
    select
        new_cycle_id,
        enrollments.student_id,
        enrollments.id,
        enrollments.class_id,
        enrollments.class_id,
        'stay',
        p_created_by,
        now()
    from public.academy_enrollments enrollments
    join public.students students
      on students.id = enrollments.student_id
    where enrollments.status in ('active', 'paused')
      and students.role = 'student'
      and students.learner_type = 'academy_student'
    order by enrollments.student_id;

    get diagnostics inserted_decision_count = row_count;

    if inserted_decision_count = 0 then
        raise exception 'placement_cycle_has_no_current_students';
    end if;

    return new_cycle_id;
end;
$$;

revoke all on function public.create_academy_placement_cycle(text, date, bigint, text)
    from public, anon, authenticated;

grant execute on function public.create_academy_placement_cycle(text, date, bigint, text)
    to service_role;

-- 5. Approve a complete and still-current draft cycle.

create or replace function public.approve_academy_placement_cycle(
    p_cycle_id bigint,
    p_approved_by bigint
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    cycle_record public.academy_placement_cycles%rowtype;
    decision_count integer;
begin
    if not exists (
        select 1
        from public.students
        where id = p_approved_by
          and role = 'admin'
    ) then
        raise exception 'placement_cycle_admin_required';
    end if;

    select *
    into cycle_record
    from public.academy_placement_cycles
    where id = p_cycle_id
    for update;

    if not found then
        raise exception 'placement_cycle_not_found';
    end if;

    if cycle_record.status <> 'draft' then
        raise exception 'placement_cycle_not_draft';
    end if;

    select count(*)::integer
    into decision_count
    from public.academy_placement_decisions
    where cycle_id = p_cycle_id;

    if decision_count = 0 then
        raise exception 'placement_cycle_has_no_decisions';
    end if;

    if exists (
        select 1
        from public.academy_placement_decisions decisions
        left join public.academy_enrollments enrollments
          on enrollments.id = decisions.enrollment_id
         and enrollments.student_id = decisions.student_id
         and enrollments.status in ('active', 'paused')
        where decisions.cycle_id = p_cycle_id
          and (
              enrollments.id is null
              or enrollments.class_id <> decisions.from_class_id
          )
    ) then
        raise exception 'placement_cycle_contains_stale_enrollment';
    end if;

    update public.academy_placement_cycles
    set status = 'approved',
        approved_by = p_approved_by,
        approved_at = now(),
        updated_at = now()
    where id = p_cycle_id;

    return jsonb_build_object(
        'cycle_id', p_cycle_id,
        'status', 'approved',
        'decision_count', decision_count,
        'effective_on', cycle_record.effective_on
    );
end;
$$;

revoke all on function public.approve_academy_placement_cycle(bigint, bigint)
    from public, anon, authenticated;

grant execute on function public.approve_academy_placement_cycle(bigint, bigint)
    to service_role;

-- 6. Apply one approved cycle atomically after its effective date arrives.

create or replace function public.apply_academy_placement_cycle(
    p_cycle_id bigint,
    p_applied_by bigint default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    cycle_record public.academy_placement_cycles%rowtype;
    decision_record record;
    enrollment_record public.academy_enrollments%rowtype;
    taipei_today date := (now() at time zone 'Asia/Taipei')::date;
    promoted_count integer := 0;
    stayed_count integer := 0;
    demoted_count integer := 0;
    graduated_count integer := 0;
begin
    if p_applied_by is not null and not exists (
        select 1
        from public.students
        where id = p_applied_by
          and role = 'admin'
    ) then
        raise exception 'placement_cycle_admin_required';
    end if;

    select *
    into cycle_record
    from public.academy_placement_cycles
    where id = p_cycle_id
    for update;

    if not found then
        raise exception 'placement_cycle_not_found';
    end if;

    if cycle_record.status = 'applied' then
        return jsonb_build_object(
            'cycle_id', p_cycle_id,
            'status', 'applied',
            'already_applied', true,
            'applied_at', cycle_record.applied_at
        );
    end if;

    if cycle_record.status <> 'approved' then
        raise exception 'placement_cycle_not_approved';
    end if;

    if cycle_record.effective_on > taipei_today then
        raise exception 'placement_cycle_effective_date_not_arrived';
    end if;

    for decision_record in
        select *
        from public.academy_placement_decisions
        where cycle_id = p_cycle_id
        order by id
    loop
        select *
        into enrollment_record
        from public.academy_enrollments
        where id = decision_record.enrollment_id
          and student_id = decision_record.student_id
          and status in ('active', 'paused')
        for update;

        if not found then
            raise exception 'placement_current_enrollment_missing_for_student_%',
                decision_record.student_id;
        end if;

        if enrollment_record.class_id <> decision_record.from_class_id then
            raise exception 'placement_current_class_changed_for_student_%',
                decision_record.student_id;
        end if;

        insert into public.academy_class_movement_history (
            cycle_id,
            decision_id,
            student_id,
            enrollment_id,
            from_class_id,
            to_class_id,
            decision,
            reason,
            effective_on,
            changed_by
        )
        values (
            p_cycle_id,
            decision_record.id,
            decision_record.student_id,
            decision_record.enrollment_id,
            decision_record.from_class_id,
            decision_record.to_class_id,
            decision_record.decision,
            decision_record.reason,
            cycle_record.effective_on,
            p_applied_by
        );

        if decision_record.decision = 'graduate' then
            update public.academy_enrollments
            set status = 'graduated',
                access_ends_at = greatest(
                    enrolled_at,
                    cycle_record.effective_on - 1
                ),
                status_changed_at = now(),
                notes = concat_ws(
                    E'\n',
                    nullif(notes, ''),
                    concat('Graduated by placement cycle #', p_cycle_id, '.')
                ),
                updated_at = now()
            where id = decision_record.enrollment_id;

            graduated_count := graduated_count + 1;
        elsif decision_record.decision = 'promote' then
            update public.academy_enrollments
            set class_id = decision_record.to_class_id,
                status_changed_at = now(),
                updated_at = now()
            where id = decision_record.enrollment_id;

            promoted_count := promoted_count + 1;
        elsif decision_record.decision = 'demote' then
            update public.academy_enrollments
            set class_id = decision_record.to_class_id,
                status_changed_at = now(),
                updated_at = now()
            where id = decision_record.enrollment_id;

            demoted_count := demoted_count + 1;
        else
            stayed_count := stayed_count + 1;
        end if;

        update public.academy_placement_decisions
        set applied_at = now(),
            updated_at = now()
        where id = decision_record.id;
    end loop;

    update public.academy_placement_cycles
    set status = 'applied',
        applied_by = p_applied_by,
        applied_at = now(),
        updated_at = now()
    where id = p_cycle_id;

    return jsonb_build_object(
        'cycle_id', p_cycle_id,
        'status', 'applied',
        'effective_on', cycle_record.effective_on,
        'promoted_count', promoted_count,
        'stayed_count', stayed_count,
        'demoted_count', demoted_count,
        'graduated_count', graduated_count,
        'total_count', promoted_count + stayed_count + demoted_count + graduated_count
    );
end;
$$;

revoke all on function public.apply_academy_placement_cycle(bigint, bigint)
    from public, anon, authenticated;

grant execute on function public.apply_academy_placement_cycle(bigint, bigint)
    to service_role;

-- 7. Scheduler entry point. A Cron job will be enabled only after the
--    admin review UI has passed end-to-end testing.

create or replace function public.apply_due_academy_placement_cycles(
    p_limit integer default 20
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    cycle_record record;
    apply_result jsonb;
    applied_results jsonb := '[]'::jsonb;
    error_results jsonb := '[]'::jsonb;
    taipei_today date := (now() at time zone 'Asia/Taipei')::date;
begin
    if p_limit is null or p_limit < 1 or p_limit > 100 then
        raise exception 'placement_cycle_limit_out_of_range';
    end if;

    for cycle_record in
        select id
        from public.academy_placement_cycles
        where status = 'approved'
          and effective_on <= taipei_today
        order by effective_on, id
        limit p_limit
    loop
        begin
            apply_result := public.apply_academy_placement_cycle(
                cycle_record.id,
                null
            );
            applied_results := applied_results || jsonb_build_array(apply_result);
        exception
            when others then
                error_results := error_results || jsonb_build_array(
                    jsonb_build_object(
                        'cycle_id', cycle_record.id,
                        'error', sqlerrm
                    )
                );
        end;
    end loop;

    return jsonb_build_object(
        'checked_on', taipei_today,
        'applied', applied_results,
        'errors', error_results
    );
end;
$$;

revoke all on function public.apply_due_academy_placement_cycles(integer)
    from public, anon, authenticated;

grant execute on function public.apply_due_academy_placement_cycles(integer)
    to service_role;

-- 8. RLS and grants. All access goes through service-role Edge Functions.

alter table public.academy_placement_cycles enable row level security;
alter table public.academy_placement_decisions enable row level security;
alter table public.academy_class_movement_history enable row level security;

revoke all on table public.academy_placement_cycles
    from public, anon, authenticated;
revoke all on table public.academy_placement_decisions
    from public, anon, authenticated;
revoke all on table public.academy_class_movement_history
    from public, anon, authenticated;

revoke all on sequence public.academy_placement_cycles_id_seq
    from public, anon, authenticated;
revoke all on sequence public.academy_placement_decisions_id_seq
    from public, anon, authenticated;
revoke all on sequence public.academy_class_movement_history_id_seq
    from public, anon, authenticated;

grant select, insert, update, delete
    on table public.academy_placement_cycles
    to service_role;
grant select, insert, update, delete
    on table public.academy_placement_decisions
    to service_role;
grant select, insert
    on table public.academy_class_movement_history
    to service_role;

grant usage, select
    on sequence public.academy_placement_cycles_id_seq
    to service_role;
grant usage, select
    on sequence public.academy_placement_decisions_id_seq
    to service_role;
grant usage, select
    on sequence public.academy_class_movement_history_id_seq
    to service_role;

-- 9. Fail fast if the fixed class catalog is incomplete.

do $$
declare
    missing_codes text[];
begin
    select array_agg(required.code order by required.code)
    into missing_codes
    from (
        values ('E1'), ('E3'), ('E5'), ('E7')
    ) as required(code)
    where not exists (
        select 1
        from public.academy_classes classes
        where classes.code = required.code
          and classes.is_active = true
    );

    if missing_codes is not null then
        raise exception 'Phase 03A failed: missing active academy classes: %',
            array_to_string(missing_codes, ', ');
    end if;
end;
$$;

commit;

select
    (select count(*) from public.academy_placement_cycles) as placement_cycle_count,
    (select count(*) from public.academy_placement_decisions) as placement_decision_count,
    (select count(*) from public.academy_class_movement_history) as class_movement_history_count,
    (
        select count(*)
        from public.academy_classes
        where code in ('E1', 'E3', 'E5', 'E7')
          and is_active = true
    ) as active_fixed_class_count;
