-- Independent physical-material storefront.
-- Store accounts use Supabase Auth and intentionally do not link to Firebase students.

alter table public.material_packages
    add column if not exists inventory_quantity integer,
    add column if not exists max_quantity_per_order integer not null default 10;

alter table public.material_packages
    drop constraint if exists material_packages_inventory_nonnegative,
    add constraint material_packages_inventory_nonnegative
        check (inventory_quantity is null or inventory_quantity >= 0),
    drop constraint if exists material_packages_max_quantity_range,
    add constraint material_packages_max_quantity_range
        check (max_quantity_per_order between 1 and 20);

create table if not exists public.store_customer_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    display_name text,
    phone text,
    stripe_customer_id text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint store_customer_profiles_email_not_blank check (btrim(email) <> '')
);

create table if not exists public.store_shipping_methods (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    fee_twd integer not null default 0 check (fee_twd >= 0),
    enabled boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.store_shipping_methods(code, name, fee_twd, enabled, sort_order)
values ('home_delivery', '台灣本島宅配', 0, true, 10)
on conflict (code) do nothing;

create table if not exists public.store_orders (
    id bigint generated by default as identity primary key,
    order_number text not null unique,
    checkout_request_id uuid not null unique,
    customer_user_id uuid not null references auth.users(id) on delete restrict,
    customer_email text not null,
    recipient_name text not null,
    recipient_phone text not null,
    postal_code text not null,
    city text not null,
    district text not null,
    address_line1 text not null,
    address_line2 text,
    delivery_note text,
    shipping_method_code text not null references public.store_shipping_methods(code) on delete restrict,
    shipping_method_name text not null,
    subtotal_twd integer not null check (subtotal_twd >= 0),
    shipping_fee_twd integer not null default 0 check (shipping_fee_twd >= 0),
    total_twd integer not null check (total_twd > 0),
    currency text not null default 'twd' check (currency = 'twd'),
    payment_status text not null default 'pending'
        check (payment_status in ('pending','paid','failed','expired','refunded')),
    fulfillment_status text not null default 'awaiting_payment'
        check (fulfillment_status in ('awaiting_payment','preparing','shipping','completed','cancelled')),
    carrier text,
    tracking_number text,
    tracking_url text,
    stripe_checkout_session_id text unique,
    stripe_payment_intent_id text,
    stripe_customer_id text,
    stripe_livemode boolean not null default false,
    checkout_expires_at timestamptz,
    inventory_reserved_at timestamptz,
    inventory_released_at timestamptz,
    paid_at timestamptz,
    shipped_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint store_orders_total_matches check (total_twd = subtotal_twd + shipping_fee_twd),
    constraint store_orders_recipient_required check (
        btrim(recipient_name) <> '' and btrim(recipient_phone) <> '' and
        btrim(postal_code) <> '' and btrim(city) <> '' and btrim(district) <> '' and btrim(address_line1) <> ''
    )
);
create index if not exists store_orders_customer_created_idx
    on public.store_orders(customer_user_id, created_at desc);
create index if not exists store_orders_fulfillment_created_idx
    on public.store_orders(fulfillment_status, created_at desc);
create unique index if not exists store_orders_payment_intent_unique_idx
    on public.store_orders(stripe_payment_intent_id)
    where stripe_payment_intent_id is not null;

create table if not exists public.store_order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.store_orders(id) on delete restrict,
    package_id bigint not null references public.material_packages(id) on delete restrict,
    package_name text not null,
    cover_url text,
    unit_price_twd integer not null check (unit_price_twd > 0),
    quantity integer not null check (quantity between 1 and 20),
    line_total_twd integer generated always as (unit_price_twd * quantity) stored,
    created_at timestamptz not null default now(),
    constraint store_order_items_package_unique unique(order_id, package_id)
);
create index if not exists store_order_items_package_idx on public.store_order_items(package_id);

create table if not exists public.store_order_status_history (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.store_orders(id) on delete cascade,
    payment_status text not null,
    fulfillment_status text not null,
    note text,
    changed_by text not null default 'system',
    created_at timestamptz not null default now(),
    constraint store_order_history_payment_status_valid
        check (payment_status in ('pending','paid','failed','expired','refunded')),
    constraint store_order_history_fulfillment_status_valid
        check (fulfillment_status in ('awaiting_payment','preparing','shipping','completed','cancelled'))
);
create index if not exists store_order_status_history_order_idx
    on public.store_order_status_history(order_id, created_at);

create or replace function public.reserve_store_order_inventory(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    current_order public.store_orders%rowtype;
    item record;
begin
    select * into current_order from public.store_orders where id = p_order_id for update;
    if not found or current_order.payment_status <> 'pending' then
        raise exception 'store_order_not_reservable';
    end if;
    if current_order.inventory_reserved_at is not null and current_order.inventory_released_at is null then
        return;
    end if;
    for item in
        select oi.package_id, oi.quantity, mp.inventory_quantity
        from public.store_order_items oi
        join public.material_packages mp on mp.id = oi.package_id
        where oi.order_id = p_order_id
        order by oi.package_id
        for update of mp
    loop
        if item.inventory_quantity is not null and item.inventory_quantity < item.quantity then
            raise exception 'store_order_inventory_insufficient';
        end if;
        if item.inventory_quantity is not null then
            update public.material_packages
            set inventory_quantity = inventory_quantity - item.quantity, updated_at = now()
            where id = item.package_id;
        end if;
    end loop;
    update public.store_orders
    set inventory_reserved_at = now(), inventory_released_at = null, updated_at = now()
    where id = p_order_id;
end;
$$;
revoke all on function public.reserve_store_order_inventory(bigint) from public, anon, authenticated;
grant execute on function public.reserve_store_order_inventory(bigint) to service_role;

create or replace function public.release_store_order_inventory(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    current_order public.store_orders%rowtype;
    item record;
begin
    select * into current_order from public.store_orders where id = p_order_id for update;
    if not found or current_order.inventory_reserved_at is null or current_order.inventory_released_at is not null then
        return;
    end if;
    for item in
        select oi.package_id, oi.quantity, mp.inventory_quantity
        from public.store_order_items oi
        join public.material_packages mp on mp.id = oi.package_id
        where oi.order_id = p_order_id
        order by oi.package_id
        for update of mp
    loop
        if item.inventory_quantity is not null then
            update public.material_packages
            set inventory_quantity = inventory_quantity + item.quantity, updated_at = now()
            where id = item.package_id;
        end if;
    end loop;
    update public.store_orders set inventory_released_at = now(), updated_at = now() where id = p_order_id;
end;
$$;
revoke all on function public.release_store_order_inventory(bigint) from public, anon, authenticated;
grant execute on function public.release_store_order_inventory(bigint) to service_role;

create or replace function public.handle_store_customer_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if new.email is null or btrim(new.email) = '' then
        return new;
    end if;
    insert into public.store_customer_profiles(user_id, email, display_name)
    values (new.id, coalesce(new.email, ''), nullif(btrim(new.raw_user_meta_data->>'display_name'), ''))
    on conflict (user_id) do update
        set email = excluded.email,
            updated_at = now();
    return new;
end;
$$;
revoke all on function public.handle_store_customer_created() from public, anon, authenticated;

drop trigger if exists store_customer_created on auth.users;
create trigger store_customer_created
after insert or update of email on auth.users
for each row execute function public.handle_store_customer_created();

create or replace function public.confirm_store_order_payment(
    p_order_id bigint,
    p_checkout_session_id text,
    p_payment_intent_id text,
    p_paid_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    current_order public.store_orders%rowtype;
begin
    select * into current_order
    from public.store_orders
    where id = p_order_id
    for update;

    if not found or current_order.stripe_checkout_session_id is distinct from p_checkout_session_id then
        raise exception 'store_order_checkout_mismatch';
    end if;
    if current_order.payment_status = 'paid' then
        return;
    end if;
    if current_order.payment_status <> 'pending' then
        raise exception 'store_order_not_payable';
    end if;

    if current_order.inventory_reserved_at is null or current_order.inventory_released_at is not null then
        raise exception 'store_order_inventory_not_reserved';
    end if;

    update public.store_orders
    set payment_status = 'paid',
        fulfillment_status = 'preparing',
        stripe_payment_intent_id = p_payment_intent_id,
        paid_at = p_paid_at,
        updated_at = now()
    where id = p_order_id;

    insert into public.store_order_status_history(
        order_id, payment_status, fulfillment_status, note, changed_by
    ) values (p_order_id, 'paid', 'preparing', 'Stripe 付款已確認，訂單進入備貨。', 'stripe_webhook');
end;
$$;
revoke all on function public.confirm_store_order_payment(bigint, text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.confirm_store_order_payment(bigint, text, text, timestamptz) to service_role;

alter table public.store_customer_profiles enable row level security;
alter table public.store_shipping_methods enable row level security;
alter table public.store_orders enable row level security;
alter table public.store_order_items enable row level security;
alter table public.store_order_status_history enable row level security;

revoke all on public.store_customer_profiles, public.store_shipping_methods,
    public.store_orders, public.store_order_items, public.store_order_status_history
from public, anon, authenticated;
grant all on public.store_customer_profiles, public.store_shipping_methods,
    public.store_orders, public.store_order_items, public.store_order_status_history
to service_role;
grant usage, select on sequence public.store_shipping_methods_id_seq,
    public.store_orders_id_seq, public.store_order_items_id_seq,
    public.store_order_status_history_id_seq to service_role;
