begin;

-- Phase 1 of the academy all-access and mixed-assignment rollout.
-- The new assignment schema is additive and remains dormant until the
-- assignment_v2 feature flag is enabled for a student.

update public.subscription_plans
set
    description = '英文班有效在學期間包含全部正式聽力教材、AI 教材、發音練習、情境會話、智慧複習及所屬班級作業。',
    ai_daily_limit = 5,
    features = coalesce(features, '{}'::jsonb) || jsonb_build_object(
        'listening', true,
        'conversation', true,
        'review', true,
        'assignments', true,
        'ai_materials', true,
        'ai_monthly_limit', 150,
        'pronunciation', true,
        'pronunciation_practice', true,
        'requires_book_entitlement', false
    ),
    updated_at = now()
where code = 'academy_internal';

update public.subscription_plans
set
    description = '購買教材附贈 90 天平台使用權；有效期間可使用全部已啟用正式教材音檔、學習進度與智慧複習，不包含班級作業、AI 教材或發音練習。',
    features = coalesce(features, '{}'::jsonb) || jsonb_build_object(
        'listening', true,
        'conversation', false,
        'review', true,
        'assignments', false,
        'ai_materials', false,
        'pronunciation', false,
        'pronunciation_practice', false,
        'requires_book_entitlement', false
    ),
    updated_at = now()
where code = 'textbook_access';

update public.subscription_plans
set
    features = coalesce(features, '{}'::jsonb) || jsonb_build_object(
        'pronunciation', false,
        'pronunciation_practice', false
    ),
    updated_at = now()
where code = 'basic_membership_monthly';

update public.subscription_plans
set
    features = coalesce(features, '{}'::jsonb) || jsonb_build_object(
        'pronunciation', true,
        'pronunciation_practice', true
    ),
    updated_at = now()
where code in ('ai_materials_addon_monthly', 'ai_materials_general_monthly');

alter table public.student_feature_rollouts
    drop constraint if exists student_feature_rollouts_key_check;
alter table public.student_feature_rollouts
    add constraint student_feature_rollouts_key_check
    check (feature_key in ('listening_rewards_v2', 'assignment_v2'));

alter table public.assignments
    add column if not exists schema_version smallint not null default 1;

alter table public.assignments
    drop constraint if exists assignments_schema_version_check;
alter table public.assignments
    add constraint assignments_schema_version_check
    check (schema_version in (1, 2));

alter table public.assignments
    drop constraint if exists assignments_source_type_check;
alter table public.assignments
    add constraint assignments_source_type_check
    check (source_type in ('ai_material', 'music_track', 'mission_pack', 'multi_activity_v2'));

alter table public.assignments
    drop constraint if exists assignments_source_target_check;
alter table public.assignments
    add constraint assignments_source_target_check
    check (
        (source_type = 'ai_material' and ai_material_id is not null and track_id is null)
        or (source_type = 'music_track' and track_id is not null and ai_material_id is null)
        or (source_type = 'mission_pack' and ai_material_id is not null and track_id is not null)
        or (source_type = 'multi_activity_v2' and ai_material_id is null and track_id is null and schema_version = 2)
    );

create table if not exists public.book_page_learning_content (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete cascade,
    page_label text not null,
    page_number integer,
    source_text text,
    pronunciation_prompts jsonb not null default '[]'::jsonb,
    status text not null default 'draft',
    version integer not null default 1,
    created_by bigint references public.students(id) on delete set null,
    updated_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint book_page_learning_content_page_label_nonempty check (btrim(page_label) <> ''),
    constraint book_page_learning_content_page_number_positive check (page_number is null or page_number > 0),
    constraint book_page_learning_content_status_check check (status in ('draft', 'published', 'archived')),
    constraint book_page_learning_content_version_positive check (version > 0),
    constraint book_page_learning_content_prompts_array check (jsonb_typeof(pronunciation_prompts) = 'array'),
    constraint book_page_learning_content_unique_version unique (book_id, page_label, version)
);

create table if not exists public.assignment_items (
    id bigint generated by default as identity primary key,
    assignment_id bigint not null references public.assignments(id) on delete cascade,
    item_type text not null,
    book_id_snapshot bigint references public.books(id) on delete set null,
    page_from_label text,
    page_to_label text,
    config jsonb not null default '{}'::jsonb,
    content_snapshot jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint assignment_items_type_check check (item_type in ('listening', 'ai_quiz', 'pronunciation')),
    constraint assignment_items_config_object check (jsonb_typeof(config) = 'object'),
    constraint assignment_items_snapshot_object check (jsonb_typeof(content_snapshot) = 'object'),
    constraint assignment_items_sort_order_nonnegative check (sort_order >= 0),
    constraint assignment_items_unique_order unique (assignment_id, sort_order)
);

create table if not exists public.assignment_ai_items (
    assignment_item_id bigint primary key references public.assignment_items(id) on delete cascade,
    ai_material_id bigint references public.ai_generated_materials(id) on delete set null,
    passing_score integer not null default 80,
    question_snapshot jsonb not null,
    created_at timestamptz not null default now(),
    constraint assignment_ai_items_passing_score_check check (passing_score between 0 and 100),
    constraint assignment_ai_items_snapshot_object check (jsonb_typeof(question_snapshot) = 'object')
);

create table if not exists public.assignment_pronunciation_prompts (
    id bigint generated by default as identity primary key,
    assignment_item_id bigint not null references public.assignment_items(id) on delete cascade,
    prompt_key text not null,
    page_label text not null,
    reference_text text not null,
    completion_mode text not null default 'practice',
    target_score integer,
    max_scored_attempts integer not null default 3,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint assignment_pronunciation_prompt_key_nonempty check (btrim(prompt_key) <> ''),
    constraint assignment_pronunciation_page_label_nonempty check (btrim(page_label) <> ''),
    constraint assignment_pronunciation_reference_nonempty check (btrim(reference_text) <> '' and char_length(reference_text) <= 500),
    constraint assignment_pronunciation_completion_mode_check check (completion_mode in ('practice', 'target_score')),
    constraint assignment_pronunciation_target_score_check check (
        (completion_mode = 'practice' and target_score is null)
        or (completion_mode = 'target_score' and target_score between 40 and 100)
    ),
    constraint assignment_pronunciation_attempt_limit_check check (max_scored_attempts between 1 and 5),
    constraint assignment_pronunciation_sort_order_nonnegative check (sort_order >= 0),
    constraint assignment_pronunciation_unique_prompt unique (assignment_item_id, prompt_key)
);

create table if not exists public.student_assignment_item_progress (
    id bigint generated by default as identity primary key,
    assignment_item_id bigint not null references public.assignment_items(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    status text not null default 'not_started',
    completed_units integer not null default 0,
    total_units integer not null default 0,
    best_score integer,
    attempt_count integer not null default 0,
    details jsonb not null default '{}'::jsonb,
    completed_at timestamptz,
    last_activity_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint student_assignment_item_progress_status_check check (status in ('not_started', 'in_progress', 'completed')),
    constraint student_assignment_item_progress_units_check check (completed_units >= 0 and total_units >= 0 and completed_units <= total_units),
    constraint student_assignment_item_progress_score_check check (best_score is null or best_score between 0 and 100),
    constraint student_assignment_item_progress_attempts_check check (attempt_count >= 0),
    constraint student_assignment_item_progress_details_object check (jsonb_typeof(details) = 'object'),
    constraint student_assignment_item_progress_unique_student unique (assignment_item_id, student_id)
);

create table if not exists public.assignment_pronunciation_attempts (
    id bigint generated by default as identity primary key,
    assignment_item_id bigint not null references public.assignment_items(id) on delete cascade,
    prompt_id bigint not null references public.assignment_pronunciation_prompts(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    attempt_key uuid not null,
    pronunciation_score numeric(5,2) not null,
    accuracy_score numeric(5,2),
    fluency_score numeric(5,2),
    completeness_score numeric(5,2),
    prosody_score numeric(5,2),
    result_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint assignment_pronunciation_score_check check (pronunciation_score between 0 and 100),
    constraint assignment_pronunciation_accuracy_check check (accuracy_score is null or accuracy_score between 0 and 100),
    constraint assignment_pronunciation_fluency_check check (fluency_score is null or fluency_score between 0 and 100),
    constraint assignment_pronunciation_completeness_check check (completeness_score is null or completeness_score between 0 and 100),
    constraint assignment_pronunciation_prosody_check check (prosody_score is null or prosody_score between 0 and 100),
    constraint assignment_pronunciation_result_object check (jsonb_typeof(result_snapshot) = 'object'),
    constraint assignment_pronunciation_attempt_idempotency unique (student_id, attempt_key)
);

alter table public.assignment_track_items
    add column if not exists assignment_item_id bigint references public.assignment_items(id) on delete cascade;

alter table public.assignment_attempts
    add column if not exists assignment_item_id bigint references public.assignment_items(id) on delete cascade;

create index if not exists book_page_learning_content_book_status_idx
    on public.book_page_learning_content(book_id, status, page_number, version desc);
create index if not exists assignment_items_assignment_type_idx
    on public.assignment_items(assignment_id, item_type, sort_order);
create index if not exists assignment_items_book_idx
    on public.assignment_items(book_id_snapshot) where book_id_snapshot is not null;
create index if not exists assignment_pronunciation_prompts_item_idx
    on public.assignment_pronunciation_prompts(assignment_item_id, sort_order);
create index if not exists student_assignment_item_progress_student_idx
    on public.student_assignment_item_progress(student_id, status, updated_at desc);
create index if not exists assignment_pronunciation_attempts_lookup_idx
    on public.assignment_pronunciation_attempts(assignment_item_id, student_id, prompt_id, created_at desc);
create index if not exists assignment_track_items_assignment_item_idx
    on public.assignment_track_items(assignment_item_id) where assignment_item_id is not null;
create index if not exists assignment_attempts_assignment_item_idx
    on public.assignment_attempts(assignment_item_id) where assignment_item_id is not null;

alter table public.book_page_learning_content enable row level security;
alter table public.assignment_items enable row level security;
alter table public.assignment_ai_items enable row level security;
alter table public.assignment_pronunciation_prompts enable row level security;
alter table public.student_assignment_item_progress enable row level security;
alter table public.assignment_pronunciation_attempts enable row level security;

revoke all on table public.book_page_learning_content from public, anon, authenticated;
revoke all on table public.assignment_items from public, anon, authenticated;
revoke all on table public.assignment_ai_items from public, anon, authenticated;
revoke all on table public.assignment_pronunciation_prompts from public, anon, authenticated;
revoke all on table public.student_assignment_item_progress from public, anon, authenticated;
revoke all on table public.assignment_pronunciation_attempts from public, anon, authenticated;

grant select, insert, update, delete on table public.book_page_learning_content to service_role;
grant select, insert, update, delete on table public.assignment_items to service_role;
grant select, insert, update, delete on table public.assignment_ai_items to service_role;
grant select, insert, update, delete on table public.assignment_pronunciation_prompts to service_role;
grant select, insert, update, delete on table public.student_assignment_item_progress to service_role;
grant select, insert, update, delete on table public.assignment_pronunciation_attempts to service_role;

grant usage, select on sequence public.book_page_learning_content_id_seq to service_role;
grant usage, select on sequence public.assignment_items_id_seq to service_role;
grant usage, select on sequence public.assignment_pronunciation_prompts_id_seq to service_role;
grant usage, select on sequence public.student_assignment_item_progress_id_seq to service_role;
grant usage, select on sequence public.assignment_pronunciation_attempts_id_seq to service_role;

create or replace function private.ae_student_can_earn_points(p_student_id bigint)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select exists (
        select 1
        from public.students student
        join public.academy_enrollments enrollment
          on enrollment.student_id = student.id
         and enrollment.status = 'active'
        where student.id = p_student_id
          and student.role = 'student'
          and student.learner_type = 'academy_student'
          and student.archived_at is null
          and coalesce(student.account_status, 'active') <> 'archived'
    );
$$;

revoke all on function private.ae_student_can_earn_points(bigint)
    from public, anon, authenticated;
grant execute on function private.ae_student_can_earn_points(bigint)
    to service_role;

-- XP remains available to every eligible learner. Positive AE Points and
-- level-up points are clamped to zero unless the student is actively enrolled.
create or replace function private.ae_gamification_grant_v2(
    p_student_id bigint,
    p_xp_delta integer,
    p_points_delta integer,
    p_source_type text,
    p_source_key text,
    p_description text default null,
    p_metadata jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_inserted integer := 0;
    v_old_xp integer := 0;
    v_old_points integer := 0;
    v_new_xp integer := 0;
    v_old_level integer := 1;
    v_new_level integer := 1;
    v_level integer;
    v_level_points integer := 0;
    v_level_points_total integer := 0;
    v_can_earn_points boolean := false;
    v_effective_points_delta integer := 0;
begin
    if p_student_id is null
       or coalesce(trim(p_source_type), '') = ''
       or coalesce(trim(p_source_key), '') = '' then
        return false;
    end if;

    v_can_earn_points := private.ae_student_can_earn_points(p_student_id);
    v_effective_points_delta := case
        when coalesce(p_points_delta, 0) > 0 and not v_can_earn_points then 0
        else coalesce(p_points_delta, 0)
    end;
    if coalesce(p_xp_delta, 0) = 0 and v_effective_points_delta = 0 then
        return false;
    end if;

    insert into public.student_gamification_balances (student_id)
    values (p_student_id)
    on conflict (student_id) do nothing;

    select balance.total_xp, balance.points_balance
    into v_old_xp, v_old_points
    from public.student_gamification_balances balance
    where balance.student_id = p_student_id
    for update;

    insert into public.student_gamification_ledger (
        student_id, xp_delta, points_delta, source_type, source_key, description, metadata
    ) values (
        p_student_id,
        coalesce(p_xp_delta, 0),
        v_effective_points_delta,
        trim(p_source_type),
        trim(p_source_key),
        nullif(trim(coalesce(p_description, '')), ''),
        coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('ae_points_eligible', v_can_earn_points)
    )
    on conflict (student_id, source_type, source_key) do nothing;

    get diagnostics v_inserted = row_count;
    if v_inserted = 0 then
        return false;
    end if;

    v_new_xp := greatest(0, v_old_xp + coalesce(p_xp_delta, 0));
    v_old_level := private.ae_level_for_xp(v_old_xp);
    v_new_level := private.ae_level_for_xp(v_new_xp);

    if v_can_earn_points and coalesce(p_xp_delta, 0) > 0 and v_new_level > v_old_level then
        for v_level in (v_old_level + 1)..v_new_level loop
            v_level_points := private.ae_level_reward_points(v_level);
            if v_level_points <= 0 then
                continue;
            end if;

            insert into public.student_gamification_ledger (
                student_id, xp_delta, points_delta, source_type, source_key, description, metadata
            ) values (
                p_student_id,
                0,
                v_level_points,
                'level_up',
                concat('level:', v_level),
                concat('首次升到 Lv.', v_level),
                jsonb_build_object('level', v_level, 'ae_points_eligible', true)
            )
            on conflict (student_id, source_type, source_key) do nothing;

            get diagnostics v_inserted = row_count;
            if v_inserted > 0 then
                v_level_points_total := v_level_points_total + v_level_points;
            end if;
        end loop;
    end if;

    update public.student_gamification_balances
    set total_xp = v_new_xp,
        points_balance = greatest(0, v_old_points + v_effective_points_delta + v_level_points_total),
        updated_at = now()
    where student_id = p_student_id;

    return true;
end;
$$;

revoke all on function private.ae_gamification_grant_v2(bigint, integer, integer, text, text, text, jsonb)
    from public, anon, authenticated;
grant execute on function private.ae_gamification_grant_v2(bigint, integer, integer, text, text, text, jsonb)
    to service_role;

comment on table public.book_page_learning_content is
'Teacher-approved page source text and pronunciation prompts. Page labels alone must never be used as AI source content.';
comment on table public.assignment_items is
'Immutable activity snapshots for mixed assignment schema version 2.';
comment on table public.assignment_pronunciation_attempts is
'Pronunciation score results only. Raw student audio is not stored.';

do $$
begin
    if not exists (
        select 1 from public.subscription_plans
        where code = 'academy_internal'
          and features ->> 'ai_materials' = 'true'
          and features ->> 'pronunciation' = 'true'
          and features ->> 'assignments' = 'true'
    ) then
        raise exception 'academy all-access feature validation failed';
    end if;

    if not exists (
        select 1 from public.subscription_plans
        where code = 'textbook_access'
          and features ->> 'listening' = 'true'
          and features ->> 'requires_book_entitlement' = 'false'
          and features ->> 'ai_materials' = 'false'
          and features ->> 'pronunciation' = 'false'
    ) then
        raise exception 'textbook 90-day all-listening validation failed';
    end if;
end;
$$;

commit;
