begin;

create table if not exists public.spiral_review_units (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete restrict,
    title text not null,
    unit_label text,
    page_start integer not null,
    page_end integer not null,
    status text not null default 'published',
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint spiral_review_units_title_nonempty check (btrim(title) <> '' and char_length(title) <= 160),
    constraint spiral_review_units_page_range check (page_start > 0 and page_end >= page_start and page_end - page_start <= 80),
    constraint spiral_review_units_status_check check (status in ('draft', 'published', 'archived'))
);

create table if not exists public.spiral_review_cards (
    id bigint generated by default as identity primary key,
    unit_id bigint not null references public.spiral_review_units(id) on delete cascade,
    card_type text not null default 'word',
    prompt_en text not null,
    meaning_zh text,
    example_sentence text,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint spiral_review_cards_type_check check (card_type in ('word', 'sentence')),
    constraint spiral_review_cards_prompt_nonempty check (btrim(prompt_en) <> '' and char_length(prompt_en) <= 240),
    constraint spiral_review_cards_meaning_length check (meaning_zh is null or char_length(meaning_zh) <= 240),
    constraint spiral_review_cards_example_length check (example_sentence is null or char_length(example_sentence) <= 500),
    constraint spiral_review_cards_sort_nonnegative check (sort_order >= 0),
    constraint spiral_review_cards_unit_prompt_unique unique (unit_id, prompt_en)
);

create table if not exists public.spiral_review_assignments (
    id bigint generated by default as identity primary key,
    unit_id bigint not null references public.spiral_review_units(id) on delete restrict,
    target_class text not null,
    assigned_date date not null default (timezone('Asia/Taipei', now()))::date,
    due_at timestamptz,
    enabled boolean not null default true,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint spiral_review_assignments_class_check check (target_class in ('E1', 'E3', 'E5', 'E7'))
);

create table if not exists public.student_spiral_review_progress (
    student_id bigint not null references public.students(id) on delete cascade,
    assignment_id bigint not null references public.spiral_review_assignments(id) on delete cascade,
    card_id bigint not null references public.spiral_review_cards(id) on delete cascade,
    review_step integer not null default 0,
    correct_count integer not null default 0,
    incorrect_count integer not null default 0,
    next_review_at date,
    mastered_at timestamptz,
    last_answered_at timestamptz,
    updated_at timestamptz not null default now(),
    primary key (student_id, assignment_id, card_id),
    constraint student_spiral_review_progress_counts check (review_step >= 0 and correct_count >= 0 and incorrect_count >= 0)
);

create table if not exists public.student_spiral_review_attempts (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    assignment_id bigint not null references public.spiral_review_assignments(id) on delete cascade,
    card_id bigint not null references public.spiral_review_cards(id) on delete restrict,
    selected_card_id bigint not null references public.spiral_review_cards(id) on delete restrict,
    request_key uuid not null,
    is_correct boolean not null,
    attempted_at timestamptz not null default now(),
    constraint student_spiral_review_attempts_request_unique unique (student_id, request_key)
);

create index if not exists spiral_review_units_book_status_idx on public.spiral_review_units(book_id, status, page_start);
create index if not exists spiral_review_units_created_by_idx on public.spiral_review_units(created_by) where created_by is not null;
create index if not exists spiral_review_cards_unit_order_idx on public.spiral_review_cards(unit_id, sort_order, id);
create index if not exists spiral_review_assignments_class_active_idx on public.spiral_review_assignments(target_class, enabled, assigned_date desc);
create index if not exists spiral_review_assignments_unit_idx on public.spiral_review_assignments(unit_id);
create index if not exists spiral_review_assignments_created_by_idx on public.spiral_review_assignments(created_by) where created_by is not null;
create index if not exists student_spiral_review_progress_due_idx on public.student_spiral_review_progress(student_id, next_review_at, assignment_id);
create index if not exists student_spiral_review_progress_assignment_idx on public.student_spiral_review_progress(assignment_id, student_id);
create index if not exists student_spiral_review_progress_card_idx on public.student_spiral_review_progress(card_id);
create index if not exists student_spiral_review_attempts_student_time_idx on public.student_spiral_review_attempts(student_id, attempted_at desc);
create index if not exists student_spiral_review_attempts_assignment_idx on public.student_spiral_review_attempts(assignment_id, student_id);
create index if not exists student_spiral_review_attempts_card_idx on public.student_spiral_review_attempts(card_id);
create index if not exists student_spiral_review_attempts_selected_card_idx on public.student_spiral_review_attempts(selected_card_id);

alter table public.spiral_review_units enable row level security;
alter table public.spiral_review_cards enable row level security;
alter table public.spiral_review_assignments enable row level security;
alter table public.student_spiral_review_progress enable row level security;
alter table public.student_spiral_review_attempts enable row level security;

revoke all on table public.spiral_review_units from public, anon, authenticated;
revoke all on table public.spiral_review_cards from public, anon, authenticated;
revoke all on table public.spiral_review_assignments from public, anon, authenticated;
revoke all on table public.student_spiral_review_progress from public, anon, authenticated;
revoke all on table public.student_spiral_review_attempts from public, anon, authenticated;

grant select, insert, update, delete on table public.spiral_review_units to service_role;
grant select, insert, update, delete on table public.spiral_review_cards to service_role;
grant select, insert, update, delete on table public.spiral_review_assignments to service_role;
grant select, insert, update, delete on table public.student_spiral_review_progress to service_role;
grant select, insert on table public.student_spiral_review_attempts to service_role;

grant usage, select on sequence public.spiral_review_units_id_seq to service_role;
grant usage, select on sequence public.spiral_review_cards_id_seq to service_role;
grant usage, select on sequence public.spiral_review_assignments_id_seq to service_role;
grant usage, select on sequence public.student_spiral_review_attempts_id_seq to service_role;

create or replace function public.submit_spiral_review_answer(
    p_student_id bigint,
    p_assignment_id bigint,
    p_card_id bigint,
    p_selected_card_id bigint,
    p_request_key uuid
)
returns table (
    is_correct boolean,
    review_step integer,
    next_review_at date,
    correct_answer text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_today date := (timezone('Asia/Taipei', now()))::date;
    v_correct boolean;
    v_current_step integer := 0;
    v_next_step integer;
    v_next_date date;
    v_answer text;
    v_existing public.student_spiral_review_attempts%rowtype;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_student_id::text || ':' || p_request_key::text, 0));

    select * into v_existing
    from public.student_spiral_review_attempts
    where student_id = p_student_id and request_key = p_request_key;

    if found then
        select c.prompt_en into v_answer from public.spiral_review_cards c where c.id = v_existing.card_id;
        return query
        select v_existing.is_correct, coalesce(p.review_step, 0), p.next_review_at, v_answer
        from public.student_spiral_review_progress p
        where p.student_id = p_student_id and p.assignment_id = p_assignment_id and p.card_id = p_card_id;
        return;
    end if;

    if not exists (
        select 1
        from public.spiral_review_assignments a
        join public.spiral_review_units u on u.id = a.unit_id and u.status = 'published'
        join public.spiral_review_cards c on c.unit_id = u.id and c.id = p_card_id
        join public.spiral_review_cards selected on selected.unit_id = u.id and selected.id = p_selected_card_id
        join public.academy_classes ac on ac.code = a.target_class and ac.is_active = true
        join public.academy_enrollments ae on ae.class_id = ac.id
        where a.id = p_assignment_id
          and a.enabled = true
          and a.assigned_date <= v_today
          and ae.student_id = p_student_id
          and ae.status = 'active'
          and (ae.scheduled_departure_at is null or ae.scheduled_departure_at > v_today)
    ) then
        raise exception 'SPIRAL_REVIEW_NOT_AVAILABLE';
    end if;

    select c.prompt_en, (p_card_id = p_selected_card_id)
    into v_answer, v_correct
    from public.spiral_review_cards c
    where c.id = p_card_id;

    select coalesce(p.review_step, 0) into v_current_step
    from public.student_spiral_review_progress p
    where p.student_id = p_student_id and p.assignment_id = p_assignment_id and p.card_id = p_card_id;

    if v_correct then
        v_next_step := least(v_current_step + 1, 5);
        v_next_date := v_today + (case v_next_step when 1 then 1 when 2 then 3 when 3 then 7 when 4 then 14 else 30 end);
    else
        v_next_step := 0;
        v_next_date := v_today + 1;
    end if;

    insert into public.student_spiral_review_attempts (
        student_id, assignment_id, card_id, selected_card_id, request_key, is_correct
    ) values (
        p_student_id, p_assignment_id, p_card_id, p_selected_card_id, p_request_key, v_correct
    );

    insert into public.student_spiral_review_progress (
        student_id, assignment_id, card_id, review_step, correct_count, incorrect_count,
        next_review_at, mastered_at, last_answered_at, updated_at
    ) values (
        p_student_id, p_assignment_id, p_card_id, v_next_step,
        case when v_correct then 1 else 0 end,
        case when v_correct then 0 else 1 end,
        v_next_date,
        case when v_correct and v_next_step = 5 then now() else null end,
        now(), now()
    )
    on conflict (student_id, assignment_id, card_id) do update set
        review_step = excluded.review_step,
        correct_count = public.student_spiral_review_progress.correct_count + case when v_correct then 1 else 0 end,
        incorrect_count = public.student_spiral_review_progress.incorrect_count + case when v_correct then 0 else 1 end,
        next_review_at = excluded.next_review_at,
        mastered_at = case when v_correct and excluded.review_step = 5 then coalesce(public.student_spiral_review_progress.mastered_at, now()) else public.student_spiral_review_progress.mastered_at end,
        last_answered_at = now(),
        updated_at = now();

    return query select v_correct, v_next_step, v_next_date, v_answer;
end;
$$;

revoke all on function public.submit_spiral_review_answer(bigint, bigint, bigint, bigint, uuid) from public, anon, authenticated;
grant execute on function public.submit_spiral_review_answer(bigint, bigint, bigint, bigint, uuid) to service_role;

comment on table public.spiral_review_units is 'Teacher-defined textbook page ranges for Stage 1 spiral review.';
comment on table public.student_spiral_review_progress is 'Per-student spaced-review state. Incorrect answers are always due again on the next Taiwan calendar day.';

commit;
