-- Additive onboarding and support workflow for Alan English.
-- Existing student accounts and academy enrollments are not modified.

create table if not exists public.academy_account_invitations (
    id bigint generated by default as identity primary key,
    token_hash text not null unique,
    token_hint text not null,
    status text not null default 'active',
    invited_email text not null,
    chinese_name text not null,
    english_name text,
    class_id smallint not null references public.academy_classes(id) on delete restrict,
    guardian_name text,
    guardian_email text,
    guardian_phone text,
    enrolled_at date not null default current_date,
    access_ends_at date,
    notes text,
    created_by bigint not null references public.students(id) on delete restrict,
    claimed_by_student_id bigint references public.students(id) on delete set null,
    expires_at timestamptz not null,
    claimed_at timestamptz,
    completed_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint academy_account_invitations_status_check
        check (status in ('active', 'claimed', 'completed', 'revoked', 'expired')),
    constraint academy_account_invitations_email_check
        check (invited_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    constraint academy_account_invitations_date_order_check
        check (access_ends_at is null or access_ends_at >= enrolled_at),
    constraint academy_account_invitations_expiry_check
        check (expires_at > created_at),
    constraint academy_account_invitations_name_length_check
        check (char_length(chinese_name) between 1 and 100),
    constraint academy_account_invitations_notes_length_check
        check (notes is null or char_length(notes) <= 1000)
);

comment on table public.academy_account_invitations is
    'Single-use academy account setup invitations. Raw tokens and passwords are never stored.';

create index if not exists academy_account_invitations_status_expiry_idx
    on public.academy_account_invitations (status, expires_at);

create index if not exists academy_account_invitations_created_by_idx
    on public.academy_account_invitations (created_by, created_at desc);

create index if not exists academy_account_invitations_claimed_student_idx
    on public.academy_account_invitations (claimed_by_student_id)
    where claimed_by_student_id is not null;

alter table public.academy_account_invitations enable row level security;
revoke all on table public.academy_account_invitations from public, anon, authenticated;
revoke all on sequence public.academy_account_invitations_id_seq from public, anon, authenticated;
grant all on table public.academy_account_invitations to service_role;
grant usage, select on sequence public.academy_account_invitations_id_seq to service_role;

create or replace function public.claim_academy_account_invitation(
    p_token_hash text,
    p_firebase_uid text,
    p_login_email text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_token_hash text := lower(btrim(coalesce(p_token_hash, '')));
    v_firebase_uid text := btrim(coalesce(p_firebase_uid, ''));
    v_login_email text := lower(btrim(coalesce(p_login_email, '')));
    v_invite public.academy_account_invitations%rowtype;
    v_class_code text;
    v_created jsonb;
    v_student_id bigint;
    v_enrollment_id bigint;
begin
    if v_token_hash = '' or v_firebase_uid = '' or v_login_email = '' then
        raise exception using errcode = '22023', message = 'invalid_invitation_claim';
    end if;

    select invitations.*
    into v_invite
    from public.academy_account_invitations as invitations
    where invitations.token_hash = v_token_hash
    for update;

    if v_invite.id is null then
        raise exception using errcode = '22023', message = 'invitation_not_found';
    end if;
    if v_invite.status <> 'active' then
        raise exception using errcode = '22023', message = 'invitation_not_active';
    end if;
    if v_invite.expires_at <= now() then
        update public.academy_account_invitations
        set status = 'expired', updated_at = now()
        where id = v_invite.id;
        raise exception using errcode = '22023', message = 'invitation_expired';
    end if;
    if lower(v_invite.invited_email) <> v_login_email then
        raise exception using errcode = '22023', message = 'invitation_email_mismatch';
    end if;

    select classes.code
    into v_class_code
    from public.academy_classes as classes
    where classes.id = v_invite.class_id
      and classes.is_active = true;

    if v_class_code is null then
        raise exception using errcode = '22023', message = 'invitation_class_unavailable';
    end if;

    v_created := public.create_academy_student_account_record(
        v_firebase_uid,
        v_login_email,
        v_invite.chinese_name,
        v_class_code,
        v_invite.created_by,
        v_invite.english_name,
        v_invite.guardian_name,
        v_invite.guardian_email,
        v_invite.guardian_phone,
        v_invite.enrolled_at,
        v_invite.access_ends_at,
        v_invite.notes
    );

    v_student_id := (v_created -> 'student' ->> 'id')::bigint;
    v_enrollment_id := (v_created -> 'enrollment' ->> 'id')::bigint;

    update public.students
    set must_change_password = false,
        temporary_password_issued_at = null,
        password_changed_at = now(),
        updated_at = now()
    where id = v_student_id;

    -- Paused enrollment keeps academy access unavailable until Firebase confirms
    -- that the invited address was verified.
    update public.academy_enrollments
    set status = 'paused',
        status_changed_at = now(),
        updated_at = now()
    where id = v_enrollment_id;

    update public.academy_account_invitations
    set status = 'claimed',
        claimed_by_student_id = v_student_id,
        claimed_at = now(),
        updated_at = now()
    where id = v_invite.id;

    return jsonb_build_object(
        'invitation_id', v_invite.id,
        'student_id', v_student_id,
        'enrollment_id', v_enrollment_id,
        'class_code', v_class_code,
        'status', 'claimed'
    );
end;
$$;

revoke all on function public.claim_academy_account_invitation(text, text, text)
    from public, anon, authenticated;
grant execute on function public.claim_academy_account_invitation(text, text, text)
    to service_role;

create or replace function public.activate_academy_account_invitation(
    p_token_hash text,
    p_firebase_uid text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_token_hash text := lower(btrim(coalesce(p_token_hash, '')));
    v_firebase_uid text := btrim(coalesce(p_firebase_uid, ''));
    v_invite public.academy_account_invitations%rowtype;
    v_student public.students%rowtype;
    v_enrollment public.academy_enrollments%rowtype;
begin
    select invitations.*
    into v_invite
    from public.academy_account_invitations as invitations
    where invitations.token_hash = v_token_hash
    for update;

    if v_invite.id is null or v_invite.status <> 'claimed' then
        raise exception using errcode = '22023', message = 'invitation_not_claimed';
    end if;

    select students.*
    into v_student
    from public.students as students
    where students.id = v_invite.claimed_by_student_id
      and students.firebase_uid = v_firebase_uid
    for key share;

    if v_student.id is null then
        raise exception using errcode = '42501', message = 'invitation_student_mismatch';
    end if;

    select enrollments.*
    into v_enrollment
    from public.academy_enrollments as enrollments
    where enrollments.student_id = v_student.id
      and enrollments.status = 'paused'
    order by enrollments.created_at desc
    limit 1
    for update;

    if v_enrollment.id is null then
        raise exception using errcode = '22023', message = 'invitation_enrollment_missing';
    end if;

    update public.academy_enrollments
    set status = 'active',
        status_changed_at = now(),
        updated_at = now()
    where id = v_enrollment.id;

    update public.academy_account_invitations
    set status = 'completed',
        completed_at = now(),
        updated_at = now()
    where id = v_invite.id;

    return jsonb_build_object(
        'invitation_id', v_invite.id,
        'student_id', v_student.id,
        'enrollment_id', v_enrollment.id,
        'status', 'completed'
    );
end;
$$;

revoke all on function public.activate_academy_account_invitation(text, text)
    from public, anon, authenticated;
grant execute on function public.activate_academy_account_invitation(text, text)
    to service_role;

create table if not exists public.support_tickets (
    id bigint generated by default as identity primary key,
    student_id bigint references public.students(id) on delete set null,
    requester_name text not null,
    requester_email text not null,
    category text not null,
    subject text not null,
    message text not null,
    status text not null default 'open',
    priority text not null default 'normal',
    admin_note text,
    resolved_by bigint references public.students(id) on delete set null,
    resolved_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint support_tickets_email_check
        check (requester_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    constraint support_tickets_category_check
        check (category in ('account', 'password', 'payment', 'activation_code', 'ai_material', 'course', 'other')),
    constraint support_tickets_status_check
        check (status in ('open', 'in_progress', 'resolved', 'closed')),
    constraint support_tickets_priority_check
        check (priority in ('normal', 'urgent')),
    constraint support_tickets_name_length_check
        check (char_length(requester_name) between 1 and 100),
    constraint support_tickets_subject_length_check
        check (char_length(subject) between 1 and 160),
    constraint support_tickets_message_length_check
        check (char_length(message) between 10 and 4000),
    constraint support_tickets_note_length_check
        check (admin_note is null or char_length(admin_note) <= 4000)
);

comment on table public.support_tickets is
    'Customer support requests submitted through the public support Edge Function.';

create index if not exists support_tickets_status_created_idx
    on public.support_tickets (status, created_at desc);

create index if not exists support_tickets_student_idx
    on public.support_tickets (student_id, created_at desc)
    where student_id is not null;

create index if not exists support_tickets_email_created_idx
    on public.support_tickets (lower(requester_email), created_at desc);

alter table public.support_tickets enable row level security;
revoke all on table public.support_tickets from public, anon, authenticated;
revoke all on sequence public.support_tickets_id_seq from public, anon, authenticated;
grant all on table public.support_tickets to service_role;
grant usage, select on sequence public.support_tickets_id_seq to service_role;

do $$
declare
    exposed_table text;
begin
    foreach exposed_table in array array[
        'academy_account_invitations',
        'support_tickets'
    ] loop
        if not exists (
            select 1
            from pg_class classes
            where classes.oid = format('public.%I', exposed_table)::regclass
              and classes.relrowsecurity = true
        ) then
            raise exception '% must have RLS enabled', exposed_table;
        end if;
    end loop;
end;
$$;
