-- Student-owned profile information is served only by Firebase-verified Edge Functions.
-- Date of birth is intentionally private: it is never exposed through leaderboard data.
alter table public.students
    add column if not exists date_of_birth date;

alter table public.students
    drop constraint if exists students_date_of_birth_reasonable;

alter table public.students
    add constraint students_date_of_birth_reasonable
    check (date_of_birth is null or date_of_birth >= date '1900-01-01');

create table if not exists public.student_notifications (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    notification_type text not null default 'system'
        check (notification_type in ('system', 'assignment', 'reward', 'birthday', 'membership')),
    title text not null check (char_length(title) between 1 and 120),
    body text not null default '' check (char_length(body) <= 1000),
    metadata jsonb not null default '{}'::jsonb,
    read_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists idx_student_notifications_inbox
    on public.student_notifications(student_id, read_at, created_at desc);

alter table public.student_notifications enable row level security;
revoke all on public.student_notifications from anon, authenticated;
grant all on public.student_notifications to service_role;

update storage.buckets
set file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp']
where id = 'student-avatars';

-- Keep the existing three-argument activation function working for already-open
-- browser tabs. The four-argument version records a new student's date of birth
-- within the same claim transaction.
create function public.claim_academy_account_invitation(
    p_token_hash text,
    p_firebase_uid text,
    p_login_email text,
    p_date_of_birth date
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_result jsonb;
    v_student_id bigint;
begin
    if p_date_of_birth is not null and p_date_of_birth > current_date then
        raise exception using errcode = '22023', message = 'invalid_date_of_birth';
    end if;

    v_result := public.claim_academy_account_invitation(
        p_token_hash,
        p_firebase_uid,
        p_login_email
    );
    v_student_id := nullif(v_result ->> 'student_id', '')::bigint;

    if v_student_id is not null and p_date_of_birth is not null then
        update public.students
        set date_of_birth = p_date_of_birth,
            updated_at = now()
        where id = v_student_id
          and firebase_uid = btrim(coalesce(p_firebase_uid, ''));
    end if;

    return v_result;
end;
$$;

revoke all on function public.claim_academy_account_invitation(text, text, text, date)
    from public, anon, authenticated;
grant execute on function public.claim_academy_account_invitation(text, text, text, date)
    to service_role;
