begin;

create table if not exists public.speaking_source_documents (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete restrict,
    title text not null,
    source_kind text not null default 'pasted_text',
    original_filename text,
    mime_type text,
    private_object_key text,
    page_count integer,
    status text not null default 'draft',
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint speaking_source_documents_title_nonempty check (btrim(title) <> ''),
    constraint speaking_source_documents_source_kind_check check (source_kind in ('pasted_text', 'pdf', 'image_batch')),
    constraint speaking_source_documents_status_check check (status in ('draft', 'ready', 'archived')),
    constraint speaking_source_documents_page_count_check check (page_count is null or page_count > 0),
    constraint speaking_source_documents_private_key_check check (private_object_key is null or btrim(private_object_key) <> '')
);

create table if not exists public.speaking_source_sections (
    id bigint generated by default as identity primary key,
    document_id bigint not null references public.speaking_source_documents(id) on delete cascade,
    unit_label text,
    page_from_label text,
    page_to_label text,
    topic text not null,
    source_text text not null,
    language_level text not null default '國小中年級',
    status text not null default 'draft',
    version integer not null default 1,
    created_by bigint references public.students(id) on delete set null,
    reviewed_by bigint references public.students(id) on delete set null,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint speaking_source_sections_topic_nonempty check (btrim(topic) <> ''),
    constraint speaking_source_sections_text_length check (char_length(btrim(source_text)) between 20 and 30000),
    constraint speaking_source_sections_level_nonempty check (btrim(language_level) <> ''),
    constraint speaking_source_sections_status_check check (status in ('draft', 'reviewed', 'archived')),
    constraint speaking_source_sections_version_positive check (version > 0),
    constraint speaking_source_sections_review_consistency check (
        (status = 'reviewed' and reviewed_by is not null and reviewed_at is not null)
        or status <> 'reviewed'
    )
);

create table if not exists public.speaking_question_sets (
    id bigint generated by default as identity primary key,
    source_section_id bigint not null references public.speaking_source_sections(id) on delete restrict,
    book_id bigint not null references public.books(id) on delete restrict,
    title text not null,
    topic text not null,
    difficulty text not null,
    status text not null default 'draft',
    version integer not null default 1,
    previous_set_id bigint references public.speaking_question_sets(id) on delete set null,
    generation_metadata jsonb not null default '{}'::jsonb,
    created_by bigint references public.students(id) on delete set null,
    reviewed_by bigint references public.students(id) on delete set null,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint speaking_question_sets_title_nonempty check (btrim(title) <> ''),
    constraint speaking_question_sets_topic_nonempty check (btrim(topic) <> ''),
    constraint speaking_question_sets_difficulty_nonempty check (btrim(difficulty) <> ''),
    constraint speaking_question_sets_status_check check (status in ('draft', 'published', 'archived')),
    constraint speaking_question_sets_version_positive check (version > 0),
    constraint speaking_question_sets_metadata_object check (jsonb_typeof(generation_metadata) = 'object'),
    constraint speaking_question_sets_publish_consistency check (
        (status = 'published' and reviewed_by is not null and published_at is not null)
        or status <> 'published'
    ),
    constraint speaking_question_sets_unique_version unique (source_section_id, version)
);

create table if not exists public.speaking_questions (
    id bigint generated by default as identity primary key,
    question_set_id bigint not null references public.speaking_question_sets(id) on delete cascade,
    question_text text not null,
    hint_zh text not null,
    keywords jsonb not null default '[]'::jsonb,
    simple_answer text not null,
    model_answer text not null,
    follow_up_question text,
    pronunciation_notes_zh text,
    accepted_intents jsonb not null default '[]'::jsonb,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint speaking_questions_question_nonempty check (btrim(question_text) <> '' and char_length(question_text) <= 800),
    constraint speaking_questions_hint_nonempty check (btrim(hint_zh) <> '' and char_length(hint_zh) <= 1200),
    constraint speaking_questions_simple_answer_nonempty check (btrim(simple_answer) <> '' and char_length(simple_answer) <= 1000),
    constraint speaking_questions_model_answer_nonempty check (btrim(model_answer) <> '' and char_length(model_answer) <= 2000),
    constraint speaking_questions_follow_up_length check (follow_up_question is null or char_length(follow_up_question) <= 800),
    constraint speaking_questions_notes_length check (pronunciation_notes_zh is null or char_length(pronunciation_notes_zh) <= 1200),
    constraint speaking_questions_keywords_array check (jsonb_typeof(keywords) = 'array'),
    constraint speaking_questions_intents_array check (jsonb_typeof(accepted_intents) = 'array'),
    constraint speaking_questions_sort_order_nonnegative check (sort_order >= 0),
    constraint speaking_questions_unique_order unique (question_set_id, sort_order)
);

create table if not exists public.speaking_generation_jobs (
    id bigint generated by default as identity primary key,
    source_section_id bigint not null references public.speaking_source_sections(id) on delete cascade,
    question_set_id bigint references public.speaking_question_sets(id) on delete set null,
    requested_by bigint references public.students(id) on delete set null,
    request_key uuid not null,
    requested_count integer not null,
    status text not null default 'processing',
    model text,
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    total_tokens integer not null default 0,
    error_code text,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint speaking_generation_jobs_count_check check (requested_count between 1 and 20),
    constraint speaking_generation_jobs_status_check check (status in ('processing', 'completed', 'failed')),
    constraint speaking_generation_jobs_tokens_nonnegative check (input_tokens >= 0 and output_tokens >= 0 and total_tokens >= 0),
    constraint speaking_generation_jobs_request_key_unique unique (request_key)
);

create index if not exists speaking_source_documents_book_status_idx on public.speaking_source_documents(book_id, status, updated_at desc);
create index if not exists speaking_source_sections_document_status_idx on public.speaking_source_sections(document_id, status, updated_at desc);
create index if not exists speaking_question_sets_book_status_idx on public.speaking_question_sets(book_id, status, updated_at desc);
create index if not exists speaking_questions_set_order_idx on public.speaking_questions(question_set_id, sort_order);
create index if not exists speaking_generation_jobs_source_created_idx on public.speaking_generation_jobs(source_section_id, created_at desc);

alter table public.speaking_source_documents enable row level security;
alter table public.speaking_source_sections enable row level security;
alter table public.speaking_question_sets enable row level security;
alter table public.speaking_questions enable row level security;
alter table public.speaking_generation_jobs enable row level security;

revoke all on table public.speaking_source_documents from public, anon, authenticated;
revoke all on table public.speaking_source_sections from public, anon, authenticated;
revoke all on table public.speaking_question_sets from public, anon, authenticated;
revoke all on table public.speaking_questions from public, anon, authenticated;
revoke all on table public.speaking_generation_jobs from public, anon, authenticated;

grant select, insert, update, delete on table public.speaking_source_documents to service_role;
grant select, insert, update, delete on table public.speaking_source_sections to service_role;
grant select, insert, update, delete on table public.speaking_question_sets to service_role;
grant select, insert, update, delete on table public.speaking_questions to service_role;
grant select, insert, update, delete on table public.speaking_generation_jobs to service_role;

grant usage, select on sequence public.speaking_source_documents_id_seq to service_role;
grant usage, select on sequence public.speaking_source_sections_id_seq to service_role;
grant usage, select on sequence public.speaking_question_sets_id_seq to service_role;
grant usage, select on sequence public.speaking_questions_id_seq to service_role;
grant usage, select on sequence public.speaking_generation_jobs_id_seq to service_role;

comment on table public.speaking_source_documents is 'Private textbook source metadata. Original files must remain private and are never exposed through the Data API.';
comment on table public.speaking_source_sections is 'Teacher-reviewed source text used to ground AI speaking question generation.';
comment on table public.speaking_question_sets is 'Versioned speaking question banks. AI output remains draft until a teacher or administrator publishes it.';
comment on table public.speaking_questions is 'Guided speaking prompts, hints, model answers and pronunciation guidance derived from reviewed textbook text.';

commit;
