create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.student_gamification_balances (
    student_id bigint primary key references public.students(id) on delete cascade,
    total_xp integer not null default 0 check (total_xp >= 0),
    points_balance integer not null default 0 check (points_balance >= 0),
    updated_at timestamptz not null default now()
);

create table if not exists public.student_gamification_ledger (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    xp_delta integer not null default 0,
    points_delta integer not null default 0,
    source_type text not null,
    source_key text not null,
    description text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint student_gamification_ledger_nonzero check (xp_delta <> 0 or points_delta <> 0),
    constraint student_gamification_ledger_unique_source unique (student_id, source_type, source_key)
);

create table if not exists public.rewards (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    image_path text,
    points_cost integer not null check (points_cost > 0),
    stock_quantity integer not null default 0 check (stock_quantity >= 0),
    enabled boolean not null default true,
    per_student_limit integer check (per_student_limit is null or per_student_limit > 0),
    applicable_classes text[] not null default '{}'::text[],
    sort_order integer not null default 0,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.reward_redemptions (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    reward_id bigint not null references public.rewards(id) on delete restrict,
    reward_name text not null,
    points_cost integer not null check (points_cost > 0),
    status text not null default 'pending' check (status in ('pending','approved','ordered','ready','completed','cancelled')),
    admin_note text,
    requested_at timestamptz not null default now(),
    approved_at timestamptz,
    ordered_at timestamptz,
    ready_at timestamptz,
    completed_at timestamptz,
    cancelled_at timestamptz,
    updated_by bigint references public.students(id) on delete set null,
    updated_at timestamptz not null default now()
);

create index if not exists idx_gamification_ledger_student_created on public.student_gamification_ledger(student_id, created_at desc);
create index if not exists idx_gamification_ledger_created on public.student_gamification_ledger(created_at desc);
create index if not exists idx_rewards_enabled_sort on public.rewards(enabled, sort_order, id);
create index if not exists idx_reward_redemptions_student on public.reward_redemptions(student_id, requested_at desc);
create index if not exists idx_reward_redemptions_status on public.reward_redemptions(status, requested_at asc);

alter table public.student_gamification_balances enable row level security;
alter table public.student_gamification_ledger enable row level security;
alter table public.rewards enable row level security;
alter table public.reward_redemptions enable row level security;

revoke all on public.student_gamification_balances from anon, authenticated;
revoke all on public.student_gamification_ledger from anon, authenticated;
revoke all on public.rewards from anon, authenticated;
revoke all on public.reward_redemptions from anon, authenticated;
grant all on public.student_gamification_balances to service_role;
grant all on public.student_gamification_ledger to service_role;
grant all on public.rewards to service_role;
grant all on public.reward_redemptions to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.student_gamification_balances (student_id)
select id from public.students where role = 'student'
on conflict (student_id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
    ('student-avatars', 'student-avatars', false, 2097152, array['image/jpeg','image/png','image/webp']),
    ('reward-images', 'reward-images', false, 4194304, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function private.ae_gamification_grant(
    p_student_id bigint,
    p_xp_delta integer,
    p_points_delta integer,
    p_source_type text,
    p_source_key text,
    p_description text default null,
    p_metadata jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
    v_inserted integer := 0;
begin
    if p_student_id is null or coalesce(trim(p_source_type), '') = '' or coalesce(trim(p_source_key), '') = '' then
        return false;
    end if;
    if coalesce(p_xp_delta, 0) = 0 and coalesce(p_points_delta, 0) = 0 then
        return false;
    end if;

    insert into public.student_gamification_ledger (
        student_id, xp_delta, points_delta, source_type, source_key, description, metadata
    ) values (
        p_student_id,
        coalesce(p_xp_delta, 0),
        coalesce(p_points_delta, 0),
        trim(p_source_type),
        trim(p_source_key),
        nullif(trim(coalesce(p_description, '')), ''),
        coalesce(p_metadata, '{}'::jsonb)
    )
    on conflict (student_id, source_type, source_key) do nothing;

    get diagnostics v_inserted = row_count;
    if v_inserted = 0 then return false; end if;

    insert into public.student_gamification_balances (student_id, total_xp, points_balance, updated_at)
    values (
        p_student_id,
        greatest(0, coalesce(p_xp_delta, 0)),
        greatest(0, coalesce(p_points_delta, 0)),
        now()
    )
    on conflict (student_id) do update set
        total_xp = greatest(0, public.student_gamification_balances.total_xp + excluded.total_xp),
        points_balance = greatest(0, public.student_gamification_balances.points_balance + excluded.points_balance),
        updated_at = now();

    return true;
end;
$$;

grant usage on schema private to service_role;
grant execute on function private.ae_gamification_grant(bigint, integer, integer, text, text, text, jsonb) to service_role;

create or replace function private.ae_gamification_track_progress_trigger()
returns trigger
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
    v_day date;
begin
    v_day := (coalesce(new.last_played_at, now()) at time zone 'Asia/Taipei')::date;

    if (tg_op = 'INSERT' and new.play_count > 0)
       or (tg_op = 'UPDATE' and new.play_count > old.play_count) then
        perform private.ae_gamification_grant(
            new.student_id,
            5,
            1,
            'listening_daily',
            concat('track:', new.track_id, ':', v_day),
            '完成今日聽力練習',
            jsonb_build_object('track_id', new.track_id, 'activity_date', v_day)
        );
    end if;

    if new.completed = true and (tg_op = 'INSERT' or old.completed is distinct from true) then
        perform private.ae_gamification_grant(
            new.student_id,
            20,
            5,
            'listening_complete',
            concat('track:', new.track_id),
            '完成音檔 7 次挑戰',
            jsonb_build_object('track_id', new.track_id)
        );
    end if;

    return new;
end;
$$;

drop trigger if exists trg_ae_gamification_track_progress on public.student_track_progress;
create trigger trg_ae_gamification_track_progress
after insert or update of play_count, completed on public.student_track_progress
for each row execute function private.ae_gamification_track_progress_trigger();

create or replace function private.ae_gamification_assignment_progress_trigger()
returns trigger
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
begin
    if new.completed = true and (tg_op = 'INSERT' or old.completed is distinct from true) then
        perform private.ae_gamification_grant(
            new.student_id,
            30,
            5,
            'assignment_complete',
            concat('assignment:', new.assignment_id),
            '完成老師作業',
            jsonb_build_object('assignment_id', new.assignment_id, 'score', new.best_score)
        );

        if new.best_score >= 90 then
            perform private.ae_gamification_grant(
                new.student_id,
                20,
                5,
                'assignment_90',
                concat('assignment:', new.assignment_id),
                '作業達成 90 分以上',
                jsonb_build_object('assignment_id', new.assignment_id, 'score', new.best_score)
            );
        end if;

        if new.best_score >= 100 then
            perform private.ae_gamification_grant(
                new.student_id,
                10,
                5,
                'assignment_100',
                concat('assignment:', new.assignment_id),
                '作業滿分獎勵',
                jsonb_build_object('assignment_id', new.assignment_id, 'score', new.best_score)
            );
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_ae_gamification_assignment_progress on public.assignment_progress;
create trigger trg_ae_gamification_assignment_progress
after insert or update of completed, best_score on public.assignment_progress
for each row execute function private.ae_gamification_assignment_progress_trigger();

create or replace function public.get_gamification_leaderboard(
    p_period text default 'week',
    p_class text default null,
    p_limit integer default 50
) returns table(
    rank_position bigint,
    student_id bigint,
    student_name text,
    class_name text,
    avatar_path text,
    period_xp bigint,
    total_xp integer,
    points_balance integer
)
language sql
security invoker
set search_path = public, pg_temp
as $$
    with bounds as (
        select case
            when p_period = 'week' then (
                (now() at time zone 'Asia/Taipei')::date
                - (extract(isodow from (now() at time zone 'Asia/Taipei')::date)::integer - 1)
            )::date
            when p_period = 'month' then date_trunc('month', (now() at time zone 'Asia/Taipei')::date)::date
            when p_period = 'all' then null::date
            else (
                (now() at time zone 'Asia/Taipei')::date
                - (extract(isodow from (now() at time zone 'Asia/Taipei')::date)::integer - 1)
            )::date
        end as start_date
    ),
    period_scores as (
        select ledger.student_id, coalesce(sum(ledger.xp_delta), 0)::bigint as period_xp
        from public.student_gamification_ledger ledger
        cross join bounds
        where bounds.start_date is null
           or ledger.created_at >= (bounds.start_date::timestamp at time zone 'Asia/Taipei')
        group by ledger.student_id
    ),
    scores as (
        select
            students.id as student_id,
            coalesce(nullif(students.english_name, ''), nullif(students.name, ''), 'Student') as student_name,
            students.class as class_name,
            students.user_image as avatar_path,
            coalesce(period_scores.period_xp, 0)::bigint as period_xp,
            coalesce(balance.total_xp, 0)::integer as total_xp,
            coalesce(balance.points_balance, 0)::integer as points_balance
        from public.students students
        left join public.student_gamification_balances balance on balance.student_id = students.id
        left join period_scores on period_scores.student_id = students.id
        where students.role = 'student'
          and coalesce(students.account_status, 'active') = 'active'
          and students.archived_at is null
          and (p_class is null or students.class = p_class)
    ),
    ranked as (
        select dense_rank() over (order by period_xp desc, total_xp desc, student_id asc)::bigint as rank_position, scores.*
        from scores
    )
    select rank_position, student_id, student_name, class_name, avatar_path, period_xp, total_xp, points_balance
    from ranked
    where rank_position <= least(greatest(coalesce(p_limit, 50), 1), 100)
    order by rank_position, student_id;
$$;

revoke all on function public.get_gamification_leaderboard(text, text, integer) from public, anon, authenticated;
grant execute on function public.get_gamification_leaderboard(text, text, integer) to service_role;

create or replace function public.request_reward_redemption(
    p_student_id bigint,
    p_reward_id bigint
) returns table(redemption_id bigint, status text, points_balance integer)
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
    v_reward public.rewards%rowtype;
    v_student public.students%rowtype;
    v_balance public.student_gamification_balances%rowtype;
    v_count integer := 0;
    v_redemption_id bigint;
begin
    select * into v_student from public.students where id = p_student_id and role = 'student' for update;
    if not found then raise exception 'STUDENT_NOT_FOUND'; end if;

    select * into v_reward from public.rewards where id = p_reward_id for update;
    if not found or v_reward.enabled is not true then raise exception 'REWARD_UNAVAILABLE'; end if;
    if v_reward.stock_quantity <= 0 then raise exception 'OUT_OF_STOCK'; end if;
    if cardinality(v_reward.applicable_classes) > 0 and not (coalesce(v_student.class, '') = any(v_reward.applicable_classes)) then
        raise exception 'CLASS_NOT_ELIGIBLE';
    end if;

    if v_reward.per_student_limit is not null then
        select count(*) into v_count
        from public.reward_redemptions
        where student_id = p_student_id
          and reward_id = p_reward_id
          and status <> 'cancelled';
        if v_count >= v_reward.per_student_limit then raise exception 'REDEMPTION_LIMIT_REACHED'; end if;
    end if;

    insert into public.student_gamification_balances(student_id)
    values (p_student_id)
    on conflict (student_id) do nothing;

    select * into v_balance from public.student_gamification_balances where student_id = p_student_id for update;
    if v_balance.points_balance < v_reward.points_cost then raise exception 'INSUFFICIENT_POINTS'; end if;

    insert into public.reward_redemptions(student_id, reward_id, reward_name, points_cost)
    values (p_student_id, v_reward.id, v_reward.name, v_reward.points_cost)
    returning id into v_redemption_id;

    update public.student_gamification_balances
    set points_balance = points_balance - v_reward.points_cost,
        updated_at = now()
    where student_id = p_student_id;

    insert into public.student_gamification_ledger(student_id, xp_delta, points_delta, source_type, source_key, description, metadata)
    values (
        p_student_id,
        0,
        -v_reward.points_cost,
        'reward_redemption',
        concat('redemption:', v_redemption_id),
        concat('兌換獎品：', v_reward.name),
        jsonb_build_object('reward_id', v_reward.id, 'redemption_id', v_redemption_id)
    );

    update public.rewards
    set stock_quantity = stock_quantity - 1,
        updated_at = now()
    where id = v_reward.id;

    return query
    select v_redemption_id, 'pending'::text, (v_balance.points_balance - v_reward.points_cost)::integer;
end;
$$;

revoke all on function public.request_reward_redemption(bigint, bigint) from public, anon, authenticated;
grant execute on function public.request_reward_redemption(bigint, bigint) to service_role;

create or replace function public.update_reward_redemption_status(
    p_redemption_id bigint,
    p_status text,
    p_admin_id bigint,
    p_note text default null
) returns table(redemption_id bigint, status text, points_balance integer)
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
    v_redemption public.reward_redemptions%rowtype;
    v_allowed boolean := false;
    v_balance integer := 0;
begin
    if p_status not in ('approved','ordered','ready','completed','cancelled') then raise exception 'INVALID_STATUS'; end if;

    select * into v_redemption from public.reward_redemptions where id = p_redemption_id for update;
    if not found then raise exception 'REDEMPTION_NOT_FOUND'; end if;

    if v_redemption.status = p_status then
        select points_balance into v_balance from public.student_gamification_balances where student_id = v_redemption.student_id;
        return query select v_redemption.id, v_redemption.status, coalesce(v_balance, 0);
        return;
    end if;

    v_allowed := case v_redemption.status
        when 'pending' then p_status in ('approved','cancelled')
        when 'approved' then p_status in ('ordered','ready','cancelled')
        when 'ordered' then p_status in ('ready','cancelled')
        when 'ready' then p_status in ('completed','cancelled')
        else false
    end;
    if not v_allowed then raise exception 'INVALID_STATUS_TRANSITION'; end if;

    if p_status = 'cancelled' then
        update public.student_gamification_balances
        set points_balance = points_balance + v_redemption.points_cost,
            updated_at = now()
        where student_id = v_redemption.student_id;

        insert into public.student_gamification_ledger(student_id, xp_delta, points_delta, source_type, source_key, description, metadata)
        values (
            v_redemption.student_id,
            0,
            v_redemption.points_cost,
            'reward_refund',
            concat('redemption:', v_redemption.id),
            concat('取消兌換退回點數：', v_redemption.reward_name),
            jsonb_build_object('reward_id', v_redemption.reward_id, 'redemption_id', v_redemption.id)
        )
        on conflict (student_id, source_type, source_key) do nothing;

        update public.rewards set stock_quantity = stock_quantity + 1, updated_at = now() where id = v_redemption.reward_id;
    end if;

    update public.reward_redemptions
    set status = p_status,
        admin_note = coalesce(nullif(trim(coalesce(p_note, '')), ''), admin_note),
        approved_at = case when p_status = 'approved' and approved_at is null then now() else approved_at end,
        ordered_at = case when p_status = 'ordered' and ordered_at is null then now() else ordered_at end,
        ready_at = case when p_status = 'ready' and ready_at is null then now() else ready_at end,
        completed_at = case when p_status = 'completed' and completed_at is null then now() else completed_at end,
        cancelled_at = case when p_status = 'cancelled' and cancelled_at is null then now() else cancelled_at end,
        updated_by = p_admin_id,
        updated_at = now()
    where id = v_redemption.id;

    select points_balance into v_balance from public.student_gamification_balances where student_id = v_redemption.student_id;
    return query select v_redemption.id, p_status, coalesce(v_balance, 0);
end;
$$;

revoke all on function public.update_reward_redemption_status(bigint, text, bigint, text) from public, anon, authenticated;
grant execute on function public.update_reward_redemption_status(bigint, text, bigint, text) to service_role;

create or replace function public.record_game_gamification(
    p_student_id bigint,
    p_game_key text,
    p_session_key text,
    p_won boolean default false
) returns table(xp_added integer, points_added integer, total_xp integer, points_balance integer)
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
    v_start timestamptz;
    v_xp_today integer := 0;
    v_points_today integer := 0;
    v_xp integer := case when p_won then 10 else 5 end;
    v_points integer := case when p_won then 2 else 1 end;
    v_granted boolean := false;
    v_balance public.student_gamification_balances%rowtype;
begin
    if coalesce(trim(p_game_key), '') = '' or coalesce(trim(p_session_key), '') = '' then raise exception 'INVALID_GAME_SESSION'; end if;

    v_start := (((now() at time zone 'Asia/Taipei')::date)::timestamp at time zone 'Asia/Taipei');
    select coalesce(sum(xp_delta), 0)::integer, coalesce(sum(points_delta), 0)::integer
    into v_xp_today, v_points_today
    from public.student_gamification_ledger
    where student_id = p_student_id and source_type = 'game' and created_at >= v_start;

    v_xp := least(v_xp, greatest(0, 30 - v_xp_today));
    v_points := least(v_points, greatest(0, 6 - v_points_today));

    if v_xp > 0 or v_points > 0 then
        v_granted := private.ae_gamification_grant(
            p_student_id,
            v_xp,
            v_points,
            'game',
            concat(trim(p_game_key), ':', trim(p_session_key)),
            case when p_won then '完成遊戲並獲勝' else '完成遊戲' end,
            jsonb_build_object('game_key', trim(p_game_key), 'won', p_won)
        );
    end if;

    select * into v_balance from public.student_gamification_balances where student_id = p_student_id;
    return query select
        case when v_granted then v_xp else 0 end,
        case when v_granted then v_points else 0 end,
        coalesce(v_balance.total_xp, 0),
        coalesce(v_balance.points_balance, 0);
end;
$$;

revoke all on function public.record_game_gamification(bigint, text, text, boolean) from public, anon, authenticated;
grant execute on function public.record_game_gamification(bigint, text, text, boolean) to service_role;