begin;

create table if not exists public.book_page_spiral_review_content (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete cascade,
    page_label text not null,
    page_number integer not null,
    source_note text not null,
    pronunciation_prompts jsonb not null default '[]'::jsonb,
    status text not null default 'draft',
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint book_page_spiral_review_page_label_nonempty check (btrim(page_label) <> ''),
    constraint book_page_spiral_review_page_number_positive check (page_number > 0),
    constraint book_page_spiral_review_source_note_nonempty check (btrim(source_note) <> ''),
    constraint book_page_spiral_review_prompts_array check (jsonb_typeof(pronunciation_prompts) = 'array'),
    constraint book_page_spiral_review_status_check check (status in ('draft', 'published', 'archived')),
    constraint book_page_spiral_review_version_positive check (version > 0),
    constraint book_page_spiral_review_unique_version unique (book_id, page_number, version)
);

create index if not exists book_page_spiral_review_lookup_idx
    on public.book_page_spiral_review_content(book_id, status, page_number, version desc);

alter table public.book_page_spiral_review_content enable row level security;
revoke all on table public.book_page_spiral_review_content from public, anon, authenticated;
grant select, insert, update, delete on table public.book_page_spiral_review_content to service_role;
grant usage, select on sequence public.book_page_spiral_review_content_id_seq to service_role;

-- Workbook 1 uses the 119-page 2026 student edition as the canonical page
-- numbering. The 109-page teacher edition is verification-only because added
-- student-edition pages make a fixed page offset unsafe.
do $$
begin
    if not exists (select 1 from public.books where code = 'Workbook_1' and content_scope = 'formal') then
        raise exception 'Workbook_1 formal book is missing';
    end if;
    if exists (
        select 1 from public.book_page_spiral_review_content content
        join public.books book on book.id = content.book_id
        where book.code = 'Workbook_1'
    ) then
        raise exception 'Workbook_1 page content already exists; review versions instead of overwriting it';
    end if;
end;
$$;

with reviewed_pages(page_number, activity_note, pronunciation_prompts) as (
    values
        (2, '學英文的原因', '["travel","make friends","work","school education","music","movies","medicine and science","the internet","learn another language"]'::jsonb),
        (10, '大小寫字母 A 到 O', '["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O"]'::jsonb),
        (12, '大小寫字母 P 到 Z', '["P","Q","R","S","T","U","V","W","X","Y","Z"]'::jsonb),
        (13, '字母順序', '["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]'::jsonb),
        (14, '單字大小寫', '["apple","juice","world","orange","purple","dance","plane","black","queen","friends"]'::jsonb),
        (15, '常用單字大小寫', '["thanks","welcome","nice","great","teacher","chair","elephant","paper","bottle","computer","sunny","weather"]'::jsonb),
        (16, '專有名詞大小寫', '["Taiwan","Chinese","McDonald''s","America","Kentucky","Starbucks","Costco","Tasty","Family","Gogoro","Microsoft","Domino''s"]'::jsonb),
        (17, '數字英文', '["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve"]'::jsonb),
        (18, '名字問答', '["What is your name?","What''s your name?","My name is Alan.","I am Alan.","I''m Alan.","Please tell me your name."]'::jsonb),
        (19, '姓氏問答', '["What is your family name?","What''s your family name?","My family name is Hsu.","What is your surname?","My surname is Hsu.","Please spell your family name."]'::jsonb),
        (20, '全名問答', '["What is your full name?","What''s your full name?","My full name is Alan Hsu.","Please tell me your full name.","Please spell your full name.","Nice to meet you."]'::jsonb),
        (26, 'Be 動詞縮寫', '["I am","I''m","you are","you''re","he is","he''s","she is","she''s","we are","we''re","they are","they''re"]'::jsonb),
        (27, '否定與縮寫', '["I am not","I''m not","you are not","you aren''t","he is not","he isn''t","she is not","she isn''t","we are not","we aren''t","they are not","they aren''t"]'::jsonb),
        (28, '顏色', '["red","orange","yellow","green","blue","purple","black","white","brown","pink","gray"]'::jsonb),
        (32, '客廳物品', '["couch","table","television","clock","lamp","picture","window","curtain","rug","chair"]'::jsonb),
        (34, '客廳物品問答', '["What is it?","Is it a vase?","What is that?","Is that a couch?","Is it a television?","Is it a family picture?","Is that a desk?","Is that a cabinet?","Is it a chair?","Is that a curtain?","Is it a bench?"]'::jsonb),
        (35, '打招呼', '["Good morning.","Good afternoon.","Good evening.","Good night.","Hello.","Hi.","Nice to meet you.","How do you do?"]'::jsonb),
        (36, '禮貌回應', '["Hello.","Great, thanks.","See you.","How do you do?","Me too.","Good afternoon.","My name is Alan."]'::jsonb),
        (39, '數字一到二十', '["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty"]'::jsonb),
        (40, '複數物品問答', '["What are these?","What are they?","They are mine.","Are they yours?","Are they mine?","Are they for me?"]'::jsonb),
        (41, '數字單字複習', '["three","nine","eleven","thirteen","seven","twelve","two","eight","five"]'::jsonb),
        (42, '英文加減法', '["seven minus two","seven plus four","five plus three","twelve minus five","two plus two","ten minus nine","four plus three minus two"]'::jsonb),
        (43, '英文加減法聽辨', '["thirteen minus seven","four and eight","nine minus eight","three plus three","two and two","eight minus three","six plus three"]'::jsonb),
        (44, '圖片數量一到十二', '["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve"]'::jsonb),
        (46, '整點時間', '["What time is it?","What is the time?","It''s one o''clock.","It''s three o''clock.","It''s six o''clock.","It''s nine o''clock.","It''s twelve o''clock."]'::jsonb),
        (47, '電話號碼讀法', '["zero","oh","one","two","three","four","five","six","seven","eight","nine","double","triple","What''s your telephone number?"]'::jsonb),
        (48, '電話號碼練習', '["area code","local number","cell phone number","mobile number","free phone number","toll-free number","double zero","triple zero"]'::jsonb),
        (49, '動物數量', '["dog","cat","frog","fish","chicken","bird","mouse","snake","How many animals are there?"]'::jsonb),
        (50, '複數物品問答', '["What are those?","What are they?","They are markers.","Are they cheap?","Are they expensive?","Are they Dad''s?","Are they Mom''s?","They are mine."]'::jsonb),
        (51, 'I am 句型', '["I am a boy.","I am a girl.","I am a man.","I am a woman.","I am Jack.","I am Mary.","I am great."]'::jsonb),
        (53, 'You are 句型', '["You are a kid.","You are a lady.","You are a student.","You are great.","You are nice.","You are students.","You are friends."]'::jsonb),
        (55, 'This is 句型', '["This is a desk.","This is a chair.","This is a pencil.","This is a pen.","This is an eraser.","This is a car.","This is a couch."]'::jsonb),
        (57, 'That is 句型', '["That is a mouse.","That is a dog.","That is a ball.","That is an apple.","That is a banana.","That is a bottle.","That is a house."]'::jsonb),
        (59, 'It is 句型', '["It is a fish.","It is a tree.","It is a horse.","It is a house.","It is a duck.","It is an elephant.","It is a monkey."]'::jsonb),
        (60, '早晨生活對話', '["Good morning.","Did you sleep well?","Are you hungry?","What''s for breakfast?","Can we play today?","What''s your plan for today?"]'::jsonb),
        (64, '身體部位句型', '["It''s my mouth.","They are my toes.","It''s my shoulder.","It''s my head.","It is my nose.","They''re my ears.","They''re my knees."]'::jsonb),
        (66, '身體與物品', '["teapot","water","cup","finger","fingers","eyes","hair","mouth","nose"]'::jsonb),
        (70, '午後生活對話', '["Good afternoon.","How''s it going?","How''s your day so far?","Did you take a nap?","Ready for a break?","It''s about teatime.","What''s your favorite?"]'::jsonb),
        (71, '時間與日常作息', '["summer","morning","afternoon","evening","get up","have breakfast","go to school","go to bed","What time is it?"]'::jsonb),
        (73, 'Jim 的日常作息', '["take a shower","have breakfast","go to school","have four classes","study math","study PE","walk home","in the afternoon"]'::jsonb),
        (75, 'Tina 的日常作息', '["walk the dog","feed the dog","take a shower","brush her teeth","go to bed","do housework","sleep through the night"]'::jsonb),
        (77, '姓名與稱謂', '["my dad","my mom","first name","family name","full name","Mr.","Mrs.","Ms.","Miss","Mount Everest"]'::jsonb),
        (78, '頭部與臉部', '["hair","head","eyes","ears","nose","mouth","teeth","eyebrows","cheeks","chin"]'::jsonb),
        (79, '英文稱謂', '["Mister","Mr. Hsu","Mrs. Chang","Ms. Chen","Miss Brown","adult male","married woman","not married"]'::jsonb),
        (80, '晚間生活對話', '["Good evening.","How was your day?","Tell me about your day.","The meal looks great.","Let''s dig in.","The food is perfect."]'::jsonb),
        (82, 'a 與 an 字母練習', '["It''s an A.","It''s a B.","It''s a C.","It''s a D.","It''s an E.","It''s an F.","It''s a G.","It''s an H.","It''s an I.","It''s a J."]'::jsonb),
        (84, '物品與場所單字', '["apple","mouse","zoo","chair","car","house","bottle","dog","elephant","girl","insect","jacket","fish","lion","octopus","pen","train","nurse","question","school","picture","bicycle","quilt","railroad","store","answer","mirror","tree","flower","apartment","yard","horse","spider","yellow"]'::jsonb),
        (85, '問候複習', '["Good morning.","Hello.","Nice to meet you.","Goodbye.","How do you do?","Good afternoon.","How are you?","Good night.","Good evening.","What is your name?"]'::jsonb),
        (87, '家庭成員', '["family","father","mother","parents","sister","brother","grandfather","grandmother","grandparents","How many people are there in your family?"]'::jsonb),
        (89, '主詞與 Be 動詞', '["I am a good student.","We are good students.","You are a smart student.","You are smart students.","He is a tall boy.","She is a pretty girl.","They are my friends.","It is my pet cat."]'::jsonb),
        (90, '睡前生活對話', '["It''s time for bed.","Good night.","I''ve already brushed my teeth.","I put on my pajamas.","Can you give me a hug?","Can you read me a story?","Can I sleep with you?"]'::jsonb),
        (92, '附加問句', '["I''m a good student, aren''t I?","We''re good students, aren''t we?","You''re a smart student, aren''t you?","He''s a tall boy, isn''t he?","She''s a pretty girl, isn''t she?","They''re my friends, aren''t they?","It''s my pet cat, isn''t it?"]'::jsonb),
        (94, '否定附加問句', '["She isn''t her mother, is she?","They aren''t her classmates, are they?","He isn''t his father, is he?","We aren''t neighbors, are we?","It isn''t your eraser, is it?","You aren''t alone, are you?"]'::jsonb),
        (96, '位置介系詞', '["in the car","on the bed","under the bed","under the table","on the bus","on the bench","in the cup","in the box","Where is it?"]'::jsonb),
        (99, 'Who are you', '["Who are you?","I''m Sam.","I am Kevin.","I''m your classmate.","My name is David.","My full name is David Chang.","How about you?"]'::jsonb),
        (100, '早安與晚安情境對話', '["Good morning, Dad.","How was your sleep?","It was great.","What''s for breakfast today?","Good night, Mom.","We have to get up early tomorrow.","Please read me a bedtime story."]'::jsonb),
        (101, '職業與地點', '["What do you do?","I am a doctor.","I am a nurse.","I am a student.","Where are you?","I am at home.","I am in my room.","I am at school.","I am in Taipei."]'::jsonb),
        (102, '人物身分與地點', '["I am on the train.","I am his mom.","I am a worker.","I am in the house.","I am at his place.","I''m your neighbor.","I am a driver.","I''m his son, Peter."]'::jsonb),
        (104, 'Who is he or she', '["Who is she?","She''s my mom.","Who is he?","He is a doctor.","What is his name?","What is her name?","His name is Johnson.","Her name is Candy."]'::jsonb),
        (105, 'Who are they', '["Who are they?","They are my friends.","We are friends.","They are teachers.","Where are they?","They are in the library.","We are in Taichung.","I am in Japan."]'::jsonb),
        (106, 'How 與 How old', '["How are you?","I''m great.","How old are you?","I''m nine years old.","How old is he?","How old is she?","What is she doing?","She is sleeping.","Where are you?"]'::jsonb),
        (108, '年齡問答', '["How old is he?","He is thirteen years old.","How old is she?","She is twelve years old.","He is a thirteen-year-old boy.","She is an eleven-year-old girl."]'::jsonb),
        (109, 'here 與 there', '["here","there","over there","The book is here.","The chair is there.","The students are over there."]'::jsonb),
        (111, 'this that these those', '["This is a lemon.","That is a watermelon.","These are peaches.","Those are pears.","What is this?","What is that?","What are these?","What are those?"]'::jsonb),
        (112, '單複數指示詞', '["This is a lemon.","These are lemons.","That is a boat.","Those are boats.","It is a candy.","It is a cookie.","They are sweets.","They are cookies."]'::jsonb),
        (114, '可數與不可數名詞', '["food","books","glasses","people","money","bread","furniture","candies","sheep"]'::jsonb),
        (117, '總複習一', '["You are a student.","What is this?","It''s an apple.","How are you?","I''m fine, thanks.","Who is that boy?","He''s Joe.","Where is Andy?"]'::jsonb),
        (118, '總複習二', '["He isn''t at home.","Is that a table?","No, it''s not.","What time is it?","How are you?","I am not so good.","What are these?","They are his new books."]'::jsonb),
        (119, '總複習三', '["Is she a beautiful woman?","Is that your pet?","No, it isn''t.","How is Ted?","He is fine.","Are you a nurse?","Yes, I am.","Is the show good?"]'::jsonb)
),
all_pages as (
    select page,
           coalesce(reviewed.activity_note,
               case
                   when page in (9, 25, 38, 62, 68, 86, 98, 116) then '歌曲頁不建立自動字卡'
                   when page in (3,4,5,6,7,8,29,33,37,45,47,49,52,54,56,58,61,63,65,67,69,72,74,76,81,83,88,91,93,95,97,103,107,110,113,115) then '描寫或單字練習空白頁，不建立自動字卡'
                   else '圖片、空格或作答內容尚不建立自動字卡'
               end) as activity_note,
           coalesce(reviewed.pronunciation_prompts, '[]'::jsonb) as pronunciation_prompts
    from generate_series(1, 119) page
    left join reviewed_pages reviewed on reviewed.page_number = page
)
insert into public.book_page_spiral_review_content (
    book_id, page_label, page_number, source_note, pronunciation_prompts,
    status, version
)
select book.id,
       'P' || all_pages.page,
       all_pages.page,
       '2026 學生新版 P' || all_pages.page || ' 已依學生版與教師版人工核對：' || all_pages.activity_note,
       all_pages.pronunciation_prompts,
       'published',
       1
from all_pages
cross join public.books book
where book.code = 'Workbook_1'
  and book.content_scope = 'formal';

do $$
begin
    if (select count(*) from public.book_page_spiral_review_content content join public.books book on book.id = content.book_id where book.code = 'Workbook_1' and content.status = 'published') <> 119 then
        raise exception 'Workbook_1 page seed must contain exactly 119 published pages';
    end if;
    if exists (
        select 1 from public.book_page_spiral_review_content content
        join public.books book on book.id = content.book_id
        where book.code = 'Workbook_1'
          and content.pronunciation_prompts::text ~ '(_{2,}|\\[\\s*\\]|Baby Shark|Twinkle Twinkle|Baa Baa Black Sheep|Cherish)'
    ) then
        raise exception 'Workbook_1 unsafe blank or song content entered the approved prompts';
    end if;
    if not exists (
        select 1 from public.book_page_spiral_review_content content
        join public.books book on book.id = content.book_id
        where book.code = 'Workbook_1'
          and jsonb_array_length(pronunciation_prompts) >= 6
    ) then
        raise exception 'Workbook_1 seed has no usable automatic-card page';
    end if;
end;
$$;

comment on table public.book_page_spiral_review_content is
'Private, human-approved card prompts for page-range spiral review. Workbook_1 follows the 119-page 2026 student edition; teacher materials are verification-only.';

commit;
