begin;

create table if not exists public.speaking_pronunciation_attempts (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    question_set_id bigint not null references public.speaking_question_sets(id) on delete cascade,
    question_id bigint not null references public.speaking_questions(id) on delete cascade,
    pronunciation_score numeric(5,2) not null check (pronunciation_score between 0 and 100),
    accuracy_score numeric(5,2) not null check (accuracy_score between 0 and 100),
    fluency_score numeric(5,2) not null check (fluency_score between 0 and 100),
    completeness_score numeric(5,2) not null check (completeness_score between 0 and 100),
    prosody_score numeric(5,2) not null check (prosody_score between 0 and 100),
    recognized_text text not null default '',
    word_results jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists speaking_pronunciation_attempts_student_question_created_idx
    on public.speaking_pronunciation_attempts(student_id, question_id, created_at desc);

alter table public.speaking_pronunciation_attempts enable row level security;
revoke all on table public.speaking_pronunciation_attempts from public, anon, authenticated;
grant select, insert on table public.speaking_pronunciation_attempts to service_role;

comment on table public.speaking_pronunciation_attempts is
    'Scores only for textbook speaking pronunciation practice. Original microphone audio is never stored.';

commit;
