begin;

alter table public.speaking_source_documents
    add column if not exists chunk_page_size integer,
    add column if not exists chunk_count integer,
    add column if not exists original_upload_status text not null default 'not_requested';

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'speaking_source_documents_chunk_page_size_check') then
        alter table public.speaking_source_documents
            add constraint speaking_source_documents_chunk_page_size_check
            check (chunk_page_size is null or chunk_page_size between 1 and 20);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'speaking_source_documents_chunk_count_check') then
        alter table public.speaking_source_documents
            add constraint speaking_source_documents_chunk_count_check
            check (chunk_count is null or chunk_count between 1 and 500);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'speaking_source_documents_original_upload_status_check') then
        alter table public.speaking_source_documents
            add constraint speaking_source_documents_original_upload_status_check
            check (original_upload_status in ('not_requested', 'uploading', 'uploaded', 'failed'));
    end if;
    if not exists (select 1 from pg_constraint where conname = 'speaking_source_documents_chunk_metadata_check') then
        alter table public.speaking_source_documents
            add constraint speaking_source_documents_chunk_metadata_check
            check ((chunk_page_size is null and chunk_count is null) or (chunk_page_size is not null and chunk_count is not null));
    end if;
end $$;

create table if not exists public.speaking_source_chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null references public.speaking_source_documents(id) on delete cascade,
    source_section_id bigint references public.speaking_source_sections(id) on delete set null,
    chunk_index integer not null,
    page_from integer not null,
    page_to integer not null,
    private_object_key text not null,
    mime_type text not null default 'application/pdf',
    byte_size bigint not null,
    status text not null default 'pending_upload',
    attempt_count integer not null default 0,
    error_code text,
    ocr_model text,
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    total_tokens integer not null default 0,
    upload_verified_at timestamptz,
    processing_started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint speaking_source_chunks_index_check check (chunk_index >= 0),
    constraint speaking_source_chunks_page_range_check check (page_from > 0 and page_to >= page_from and page_to - page_from < 20),
    constraint speaking_source_chunks_object_key_check check (btrim(private_object_key) <> ''),
    constraint speaking_source_chunks_mime_check check (mime_type = 'application/pdf'),
    constraint speaking_source_chunks_byte_size_check check (byte_size between 1 and 20971520),
    constraint speaking_source_chunks_status_check check (status in ('pending_upload', 'uploaded', 'processing', 'review_required', 'completed', 'failed')),
    constraint speaking_source_chunks_attempt_check check (attempt_count between 0 and 100),
    constraint speaking_source_chunks_tokens_check check (input_tokens >= 0 and output_tokens >= 0 and total_tokens >= 0),
    constraint speaking_source_chunks_document_index_unique unique (document_id, chunk_index),
    constraint speaking_source_chunks_section_unique unique (source_section_id)
);

create index if not exists speaking_source_chunks_document_status_idx
    on public.speaking_source_chunks(document_id, status, chunk_index);
create index if not exists speaking_source_chunks_status_updated_idx
    on public.speaking_source_chunks(status, updated_at);

alter table public.speaking_source_chunks enable row level security;

revoke all on table public.speaking_source_chunks from public, anon, authenticated;
grant select, insert, update, delete on table public.speaking_source_chunks to service_role;
grant usage, select on sequence public.speaking_source_chunks_id_seq to service_role;

comment on table public.speaking_source_chunks is
    'Private ten-page PDF chunks and resumable OCR state for whole-book speaking source ingestion.';
comment on column public.speaking_source_chunks.private_object_key is
    'Private Cloudflare R2 object key. Chunk files must never receive a public URL.';

commit;
