-- Membership continuity, class materials and material commerce.
-- Additive only: ownership rows and access grants are intentionally separate ledgers.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to service_role;

alter table public.academy_enrollments
    add column if not exists scheduled_departure_at date,
    add column if not exists departed_at date,
    add column if not exists departure_reason text,
    add column if not exists departure_scheduled_by bigint references public.students(id) on delete set null,
    add column if not exists departure_completed_by bigint references public.students(id) on delete set null;

alter table public.academy_enrollments
    drop constraint if exists academy_enrollments_departure_dates_check;
alter table public.academy_enrollments
    add constraint academy_enrollments_departure_dates_check check (
        (scheduled_departure_at is null or scheduled_departure_at >= enrolled_at)
        and (departed_at is null or departed_at >= enrolled_at)
    );

create index if not exists academy_enrollments_scheduled_departure_idx
    on public.academy_enrollments(scheduled_departure_at, student_id)
    where scheduled_departure_at is not null and status in ('active', 'paused');

create table if not exists public.academy_enrollment_lifecycle_events (
    id bigint generated by default as identity primary key,
    enrollment_id bigint not null references public.academy_enrollments(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    event_type text not null check (event_type in (
        'departure_scheduled', 'departure_cancelled', 'departed', 'restored'
    )),
    effective_date date,
    impact_snapshot jsonb not null default '{}'::jsonb,
    reason text,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now()
);
create index if not exists academy_lifecycle_student_idx
    on public.academy_enrollment_lifecycle_events(student_id, created_at desc);

create table if not exists public.teacher_class_permissions (
    id bigint generated by default as identity primary key,
    teacher_id bigint not null references public.students(id) on delete cascade,
    class_id smallint not null references public.academy_classes(id) on delete cascade,
    starts_at date not null default current_date,
    ends_at date,
    can_publish boolean not null default true,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint teacher_class_permission_dates_check check (ends_at is null or ends_at >= starts_at),
    constraint teacher_class_permission_unique unique(teacher_id, class_id, starts_at)
);
create index if not exists teacher_class_permissions_active_idx
    on public.teacher_class_permissions(teacher_id, class_id, starts_at, ends_at)
    where can_publish;

insert into public.teacher_class_permissions(teacher_id, class_id, created_by)
select teacher.id, class.id, teacher.id
from public.students teacher
join public.academy_classes class on class.code = teacher.class
where teacher.role = 'teacher' and class.code in ('E1','E3','E5','E7')
on conflict (teacher_id, class_id, starts_at) do nothing;

create table if not exists public.academy_class_material_settings (
    id bigint generated by default as identity primary key,
    class_id smallint not null references public.academy_classes(id) on delete restrict,
    version integer not null,
    effective_from date not null,
    effective_to date,
    is_active boolean not null default true,
    note text,
    created_by bigint references public.students(id) on delete set null,
    updated_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint academy_class_material_setting_dates_check check (
        effective_to is null or effective_to >= effective_from
    ),
    constraint academy_class_material_setting_version_unique unique(class_id, version),
    constraint academy_class_material_setting_effective_unique unique(class_id, effective_from)
);
create index if not exists academy_class_material_settings_current_idx
    on public.academy_class_material_settings(class_id, effective_from desc, effective_to)
    where is_active;

create table if not exists public.academy_class_material_books (
    id bigint generated by default as identity primary key,
    setting_id bigint not null references public.academy_class_material_settings(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete restrict,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint academy_class_material_books_unique unique(setting_id, book_id)
);
create index if not exists academy_class_material_books_book_idx
    on public.academy_class_material_books(book_id, setting_id);

create table if not exists public.academy_class_material_audit_log (
    id bigint generated by default as identity primary key,
    class_id smallint not null references public.academy_classes(id) on delete restrict,
    setting_id bigint references public.academy_class_material_settings(id) on delete set null,
    action text not null check(action in ('created','activated','replaced','deactivated')),
    previous_snapshot jsonb not null default '{}'::jsonb,
    next_snapshot jsonb not null default '{}'::jsonb,
    affected_student_count integer not null default 0,
    affected_assignment_count integer not null default 0,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now()
);
create index if not exists academy_class_material_audit_class_idx
    on public.academy_class_material_audit_log(class_id, created_at desc);

alter table public.books
    add column if not exists content_scope text not null default 'formal',
    add column if not exists description text,
    add column if not exists preview_image_url text;
alter table public.books
    drop constraint if exists books_content_scope_check;
alter table public.books
    add constraint books_content_scope_check check(content_scope in ('formal','trial','showcase'));

alter table public.music_tracks
    add column if not exists transcript_en text,
    add column if not exists transcript_zh text,
    add column if not exists subtitle_cues jsonb not null default '[]'::jsonb,
    add column if not exists subtitle_status text not null default 'none',
    add column if not exists preview_enabled boolean not null default false;
alter table public.music_tracks
    drop constraint if exists music_tracks_subtitle_status_check;
alter table public.music_tracks
    add constraint music_tracks_subtitle_status_check check(subtitle_status in ('none','draft','published'));

create table if not exists public.student_book_entitlements (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete restrict,
    source text not null check(source in (
        'material_purchase','admin_grant','activation_code','trial','legacy'
    )),
    source_reference_type text,
    source_reference_id bigint,
    status text not null default 'active' check(status in ('pending','active','expired','revoked')),
    is_permanent boolean not null default true,
    starts_at timestamptz not null default now(),
    ends_at timestamptz,
    revoked_at timestamptz,
    revoke_reason text,
    metadata jsonb not null default '{}'::jsonb,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint student_book_entitlement_dates_check check(ends_at is null or ends_at > starts_at),
    constraint student_book_entitlement_source_pair_check check(
        (source_reference_type is null and source_reference_id is null)
        or (nullif(btrim(source_reference_type),'') is not null and source_reference_id is not null)
    )
);
create unique index if not exists student_book_entitlement_source_unique
    on public.student_book_entitlements(
        student_id, book_id, source, source_reference_type, source_reference_id
    ) nulls not distinct;
create index if not exists student_book_entitlement_active_idx
    on public.student_book_entitlements(student_id, book_id, starts_at, ends_at)
    where status = 'active';

create table if not exists public.material_packages (
    id bigint generated by default as identity primary key,
    name text not null,
    level_code text,
    suitable_for text,
    learning_goals text not null default '',
    description text not null default '',
    cover_url text,
    prerequisite_package_id bigint references public.material_packages(id) on delete set null,
    next_package_id bigint references public.material_packages(id) on delete set null,
    recommendation_rank integer not null default 0,
    standard_price_twd integer,
    member_price_twd integer,
    includes_90_day_access boolean not null default true,
    status text not null default 'draft' check(status in ('draft','published','discontinued')),
    stripe_product_id text,
    stripe_standard_price_id text,
    stripe_member_price_id text,
    stripe_livemode boolean not null default false,
    created_by bigint references public.students(id) on delete set null,
    updated_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint material_package_name_not_blank check(btrim(name) <> ''),
    constraint material_package_prices_positive check(
        (standard_price_twd is null or standard_price_twd > 0)
        and (member_price_twd is null or member_price_twd > 0)
        and (standard_price_twd is null or member_price_twd is null or member_price_twd <= standard_price_twd)
    )
);
create index if not exists material_packages_catalog_idx
    on public.material_packages(status, recommendation_rank, id);

create table if not exists public.material_package_books (
    id bigint generated by default as identity primary key,
    package_id bigint not null references public.material_packages(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete restrict,
    role text not null check(role in ('workbook','listening_book','web_material')),
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint material_package_books_unique unique(package_id, book_id, role)
);
create index if not exists material_package_books_book_idx on public.material_package_books(book_id);

create table if not exists public.material_package_tracks (
    id bigint generated by default as identity primary key,
    package_id bigint not null references public.material_packages(id) on delete cascade,
    track_id bigint not null references public.music_tracks(id) on delete restrict,
    role text not null check(role in ('included_audio','sample_audio')),
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint material_package_tracks_unique unique(package_id, track_id, role)
);

create table if not exists public.material_purchases (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete restrict,
    package_id bigint not null references public.material_packages(id) on delete restrict,
    status text not null default 'pending' check(status in ('pending','paid','failed','refunded','cancelled')),
    price_type text not null check(price_type in ('standard','member')),
    amount_twd integer not null check(amount_twd > 0),
    currency text not null default 'twd' check(currency = 'twd'),
    includes_90_day_access boolean not null default false,
    package_snapshot jsonb not null default '{}'::jsonb,
    stripe_checkout_session_id text unique,
    stripe_payment_intent_id text,
    stripe_livemode boolean not null default false,
    paid_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists material_purchases_student_idx
    on public.material_purchases(student_id, created_at desc);

create table if not exists public.material_purchase_entitlements (
    id bigint generated by default as identity primary key,
    purchase_id bigint not null references public.material_purchases(id) on delete restrict,
    book_entitlement_id bigint not null references public.student_book_entitlements(id) on delete restrict,
    created_at timestamptz not null default now(),
    constraint material_purchase_entitlement_unique unique(purchase_id, book_entitlement_id)
);

alter table public.assignments add column if not exists class_material_setting_id bigint
    references public.academy_class_material_settings(id) on delete set null;
alter table public.assignment_track_items
    add column if not exists book_id_snapshot bigint references public.books(id) on delete set null,
    add column if not exists track_id_snapshot bigint references public.music_tracks(id) on delete set null;
create index if not exists assignments_class_material_setting_idx
    on public.assignments(class_material_setting_id);

create table if not exists public.placement_assessments (
    id bigint generated by default as identity primary key,
    name text not null,
    status text not null default 'draft' check(status in ('draft','published','archived')),
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create table if not exists public.placement_questions (
    id bigint generated by default as identity primary key,
    assessment_id bigint not null references public.placement_assessments(id) on delete cascade,
    skill text not null check(skill in ('vocabulary','sentence','listening')),
    prompt text not null,
    audio_prompt text,
    track_id bigint references public.music_tracks(id) on delete set null,
    choices jsonb not null,
    correct_choice integer not null,
    difficulty integer not null default 1 check(difficulty between 1 and 5),
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint placement_listening_prompt_check check(
        skill <> 'listening' or track_id is not null or nullif(btrim(audio_prompt),'') is not null
    )
);
create table if not exists public.placement_attempts (
    id bigint generated by default as identity primary key,
    assessment_id bigint not null references public.placement_assessments(id) on delete restrict,
    student_id bigint references public.students(id) on delete set null,
    anonymous_key text,
    answers jsonb not null default '{}'::jsonb,
    skill_scores jsonb not null default '{}'::jsonb,
    recommended_package_id bigint references public.material_packages(id) on delete set null,
    manual_package_id bigint references public.material_packages(id) on delete set null,
    adjusted_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now()
);

with assessment as (
    insert into public.placement_assessments(name,status)
    select 'Alan English 三向程度推薦','published'
    where not exists (
        select 1 from public.placement_assessments where name='Alan English 三向程度推薦'
    ) returning id
), chosen as (
    select id from assessment union all
    select id from public.placement_assessments where name='Alan English 三向程度推薦' limit 1
)
insert into public.placement_questions(assessment_id,skill,prompt,audio_prompt,choices,correct_choice,difficulty,sort_order)
select chosen.id, seed.skill, seed.prompt, seed.audio_prompt, seed.choices::jsonb,
       seed.correct_choice, seed.difficulty, seed.sort_order
from chosen
cross join (values
 ('vocabulary','Which word means「快速的」?',null,'["slow","quick","quiet"]',1,1,10),
 ('vocabulary','Which word means「圖書館」?',null,'["library","kitchen","station"]',0,2,20),
 ('sentence','Choose the correct sentence.',null,'["She go to school.","She goes to school.","She going school."]',1,2,30),
 ('sentence','Tomorrow, we ___ home.',null,'["stay","stayed","will stay"]',2,3,40),
 ('listening','Listen and choose what you heard.','The blue bird is sitting by the window.','["The bird is by the window.","The bird is under the table.","The bird is in the garden."]',0,2,50),
 ('listening','Listen and choose what you heard.','Mia finished her homework before dinner.','["Mia started dinner first.","Mia finished homework before dinner.","Mia forgot her homework."]',1,3,60)
) as seed(skill,prompt,audio_prompt,choices,correct_choice,difficulty,sort_order)
where not exists(select 1 from public.placement_questions where assessment_id=chosen.id);

alter table public.student_notifications add column if not exists event_key text;
create unique index if not exists student_notifications_event_key_unique
    on public.student_notifications(student_id, event_key) where event_key is not null;

create table if not exists public.notification_events (
    id bigint generated by default as identity primary key,
    event_key text not null unique,
    student_id bigint not null references public.students(id) on delete cascade,
    event_type text not null check(event_type in (
        'material_access_expiring','subscription_expiring','subscription_cancelled',
        'subscription_expired','payment_failed','departure_scheduled'
    )),
    effective_at timestamptz,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists notification_events_student_idx
    on public.notification_events(student_id, created_at desc);

create table if not exists public.email_delivery_queue (
    id bigint generated by default as identity primary key,
    notification_event_id bigint not null references public.notification_events(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    recipient_email text not null,
    template_key text not null,
    template_data jsonb not null default '{}'::jsonb,
    status text not null default 'pending' check(status in ('pending','sending','sent','failed','skipped')),
    provider text,
    provider_message_id text,
    attempt_count integer not null default 0,
    last_error text,
    next_attempt_at timestamptz not null default now(),
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint email_delivery_queue_event_unique unique(notification_event_id, recipient_email)
);
create index if not exists email_delivery_queue_pending_idx
    on public.email_delivery_queue(status, next_attempt_at) where status in ('pending','failed');

create table if not exists public.commerce_audit_log (
    id bigint generated by default as identity primary key,
    actor_id bigint references public.students(id) on delete set null,
    action text not null,
    entity_type text not null,
    entity_id bigint,
    before_snapshot jsonb not null default '{}'::jsonb,
    after_snapshot jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists commerce_audit_entity_idx
    on public.commerce_audit_log(entity_type, entity_id, created_at desc);

alter table public.activation_codes add column if not exists book_id bigint
    references public.books(id) on delete restrict;
alter table public.activation_code_redemptions add column if not exists book_entitlement_id bigint
    references public.student_book_entitlements(id) on delete set null;
create index if not exists activation_codes_book_idx on public.activation_codes(book_id) where book_id is not null;

insert into public.subscription_plans(
    code,name,description,price_twd,billing_interval,trial_days,ai_daily_limit,
    stripe_price_id,features,is_public,enabled,sort_order,access_model
) values (
    'material_bonus_90_day','教材附贈 90 天網站使用權',
    '自教材兌換日起算 90 天，不自動續費。教材擁有權永久保留。',
    null,'month',0,0,null,
    '{"listening":true,"conversation":true,"review":true,"assignments":false,"ai_materials":false,"requires_book_entitlement":true}'::jsonb,
    false,true,90,'textbook'
) on conflict(code) do update set
    name=excluded.name, description=excluded.description, price_twd=null,
    stripe_price_id=null, features=excluded.features, is_public=false,
    enabled=true, access_model='textbook', updated_at=now();

create or replace function private.enforce_material_package_publishable()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare workbook_count integer; listening_count integer;
begin
    if new.status <> 'published' then return new; end if;
    select count(*) filter(where role='workbook'), count(*) filter(where role='listening_book')
      into workbook_count,listening_count from public.material_package_books where package_id=new.id;
    if new.standard_price_twd is null or new.member_price_twd is null
       or nullif(btrim(coalesce(new.stripe_product_id,'')),'') is null
       or nullif(btrim(coalesce(new.stripe_standard_price_id,'')),'') is null
       or nullif(btrim(coalesce(new.stripe_member_price_id,'')),'') is null
       or new.stripe_livemode <> false or workbook_count <> 1 or listening_count <> 1 then
        raise exception using errcode='23514', message='material_package_incomplete';
    end if;
    return new;
end; $$;
drop trigger if exists material_packages_publishable on public.material_packages;
create trigger material_packages_publishable before insert or update of status on public.material_packages
for each row execute function private.enforce_material_package_publishable();

create or replace function private.is_student_book_authorized(p_student_id bigint,p_book_id bigint,p_at timestamptz default now())
returns boolean language sql stable security definer set search_path=public,private,pg_temp as $$
    select exists(
        select 1 from public.student_book_entitlements e
        where e.student_id=p_student_id and e.book_id=p_book_id and e.status='active'
          and e.starts_at<=p_at and (e.is_permanent or e.ends_at is null or e.ends_at>p_at)
          and e.revoked_at is null
    ) or exists(
        select 1 from public.academy_enrollments e
        join public.academy_class_material_settings s on s.class_id=e.class_id and s.is_active
        join public.academy_class_material_books b on b.setting_id=s.id and b.book_id=p_book_id
        where e.student_id=p_student_id and e.status='active'
          and e.enrolled_at<=p_at::date and (e.access_ends_at is null or e.access_ends_at>=p_at::date)
          and (e.scheduled_departure_at is null or e.scheduled_departure_at>p_at::date)
          and s.effective_from<=p_at::date and (s.effective_to is null or s.effective_to>=p_at::date)
    ) or exists(
        select 1 from public.academy_enrollments e
        join public.academy_classes c on c.id=e.class_id
        join public.assignments a on a.target_class=c.code and a.enabled
        join public.assignment_track_items i on i.assignment_id=a.id
        where e.student_id=p_student_id and coalesce(i.book_id_snapshot,
            (select mt.book_id from public.music_tracks mt where mt.id=coalesce(i.track_id_snapshot,i.track_id)))=p_book_id
          and (a.due_at is null or a.due_at>p_at)
    );
$$;
revoke all on function private.is_student_book_authorized(bigint,bigint,timestamptz) from public,anon,authenticated;
grant execute on function private.is_student_book_authorized(bigint,bigint,timestamptz) to service_role;

-- All writes and sensitive reads are performed by Firebase-verified Edge Functions.
alter table public.academy_enrollment_lifecycle_events enable row level security;
alter table public.teacher_class_permissions enable row level security;
alter table public.academy_class_material_settings enable row level security;
alter table public.academy_class_material_books enable row level security;
alter table public.academy_class_material_audit_log enable row level security;
alter table public.student_book_entitlements enable row level security;
alter table public.material_packages enable row level security;
alter table public.material_package_books enable row level security;
alter table public.material_package_tracks enable row level security;
alter table public.material_purchases enable row level security;
alter table public.material_purchase_entitlements enable row level security;
alter table public.placement_assessments enable row level security;
alter table public.placement_questions enable row level security;
alter table public.placement_attempts enable row level security;
alter table public.notification_events enable row level security;
alter table public.email_delivery_queue enable row level security;
alter table public.commerce_audit_log enable row level security;

revoke all on table public.academy_enrollment_lifecycle_events,public.teacher_class_permissions,
 public.academy_class_material_settings,public.academy_class_material_books,public.academy_class_material_audit_log,
 public.student_book_entitlements,public.material_packages,public.material_package_books,public.material_package_tracks,
 public.material_purchases,public.material_purchase_entitlements,public.placement_assessments,public.placement_questions,
 public.placement_attempts,public.notification_events,public.email_delivery_queue,public.commerce_audit_log
from anon,authenticated;
grant all on table public.academy_enrollment_lifecycle_events,public.teacher_class_permissions,
 public.academy_class_material_settings,public.academy_class_material_books,public.academy_class_material_audit_log,
 public.student_book_entitlements,public.material_packages,public.material_package_books,public.material_package_tracks,
 public.material_purchases,public.material_purchase_entitlements,public.placement_assessments,public.placement_questions,
 public.placement_attempts,public.notification_events,public.email_delivery_queue,public.commerce_audit_log
to service_role;

do $$ declare item text; begin
    foreach item in array array[
      'teacher_class_permissions','academy_class_material_settings','student_book_entitlements',
      'material_packages','material_purchases','email_delivery_queue'
    ] loop
      execute format('drop trigger if exists %I_set_updated_at on public.%I',item,item);
      execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at_now()',item,item);
    end loop;
end $$;
