-- Stage 1: username login for academy students, one-time activation/recovery,
-- and server-side email request throttling. Existing accounts remain email-based.

alter table public.students
    add column if not exists login_username text,
    add column if not exists authentication_method text not null default 'email',
    add column if not exists activated_at timestamptz;

alter table public.students
    drop constraint if exists students_authentication_method_check;

alter table public.students
    add constraint students_authentication_method_check
    check (authentication_method in ('email', 'academy_username')) not valid;

alter table public.students
    validate constraint students_authentication_method_check;

create unique index if not exists students_login_username_lower_key
    on public.students (lower(btrim(login_username)))
    where login_username is not null;

comment on column public.students.login_username is
    'Public login identifier for academy students. The Firebase internal email must not be shown to students.';
comment on column public.students.authentication_method is
    'email for regular accounts; academy_username for academy username plus six-digit PIN accounts.';
comment on column public.students.activated_at is
    'First successful activation time for academy username accounts.';

create table if not exists public.academy_student_activation_tokens (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    token_hash char(64) not null unique,
    token_hint text not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    revoked_at timestamptz,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint academy_student_activation_token_hint_check
        check (char_length(token_hint) between 4 and 12),
    constraint academy_student_activation_expiry_check
        check (expires_at > created_at)
);

create unique index if not exists academy_student_one_active_activation_idx
    on public.academy_student_activation_tokens(student_id)
    where used_at is null and revoked_at is null;
create index if not exists academy_student_activation_student_idx
    on public.academy_student_activation_tokens(student_id, created_at desc);

create table if not exists public.academy_student_recovery_codes (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    code_hash char(64) not null unique,
    code_hint text not null,
    used_at timestamptz,
    revoked_at timestamptz,
    created_by bigint references public.students(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint academy_student_recovery_code_hint_check
        check (char_length(code_hint) between 4 and 12)
);

create index if not exists academy_student_recovery_student_idx
    on public.academy_student_recovery_codes(student_id, created_at desc);

create table if not exists public.auth_email_requests (
    id bigint generated by default as identity primary key,
    request_kind text not null,
    identifier_hash char(64) not null,
    source_hash char(64),
    requested_at timestamptz not null default now(),
    delivered_at timestamptz,
    provider_message_id text,
    status text not null default 'requested',
    constraint auth_email_request_kind_check
        check (request_kind in ('verification', 'password_reset')),
    constraint auth_email_request_status_check
        check (status in ('requested', 'sent', 'failed'))
);

create index if not exists auth_email_requests_throttle_idx
    on public.auth_email_requests(identifier_hash, request_kind, requested_at desc);
create index if not exists auth_email_requests_source_throttle_idx
    on public.auth_email_requests(source_hash, request_kind, requested_at desc)
    where source_hash is not null;

alter table public.academy_student_activation_tokens enable row level security;
alter table public.academy_student_recovery_codes enable row level security;
alter table public.auth_email_requests enable row level security;

revoke all on public.academy_student_activation_tokens from public, anon, authenticated;
revoke all on public.academy_student_recovery_codes from public, anon, authenticated;
revoke all on public.auth_email_requests from public, anon, authenticated;
revoke all on sequence public.academy_student_activation_tokens_id_seq from public, anon, authenticated;
revoke all on sequence public.academy_student_recovery_codes_id_seq from public, anon, authenticated;
revoke all on sequence public.auth_email_requests_id_seq from public, anon, authenticated;

grant select, insert, update, delete on public.academy_student_activation_tokens to service_role;
grant select, insert, update, delete on public.academy_student_recovery_codes to service_role;
grant select, insert, update, delete on public.auth_email_requests to service_role;
grant usage, select on sequence public.academy_student_activation_tokens_id_seq to service_role;
grant usage, select on sequence public.academy_student_recovery_codes_id_seq to service_role;
grant usage, select on sequence public.auth_email_requests_id_seq to service_role;

create or replace function public.create_academy_student_login_record(
    p_firebase_uid text,
    p_internal_email text,
    p_login_username text,
    p_chinese_name text,
    p_class_code text,
    p_created_by bigint,
    p_activation_token_hash text,
    p_activation_token_hint text,
    p_activation_expires_at timestamptz,
    p_recovery_code_hashes text[],
    p_recovery_code_hints text[],
    p_english_name text default null,
    p_guardian_name text default null,
    p_guardian_email text default null,
    p_guardian_phone text default null,
    p_enrolled_at date default current_date,
    p_access_ends_at date default null,
    p_notes text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_username text := lower(btrim(coalesce(p_login_username, '')));
    v_result jsonb;
    v_student_id bigint;
    v_student public.students%rowtype;
    v_index integer;
begin
    if v_username !~ '^[a-z][a-z0-9]{4,31}$' then
        raise exception using errcode = '22023', message = 'invalid_login_username';
    end if;
    if coalesce(array_length(p_recovery_code_hashes, 1), 0) <> 2
        or coalesce(array_length(p_recovery_code_hints, 1), 0) <> 2 then
        raise exception using errcode = '22023', message = 'invalid_recovery_codes';
    end if;

    v_result := public.create_academy_student_account_record(
        p_firebase_uid,
        p_internal_email,
        p_chinese_name,
        p_class_code,
        p_created_by,
        p_english_name,
        p_guardian_name,
        p_guardian_email,
        p_guardian_phone,
        p_enrolled_at,
        p_access_ends_at,
        p_notes
    );
    v_student_id := (v_result -> 'student' ->> 'id')::bigint;

    update public.students
    set login_username = v_username,
        authentication_method = 'academy_username',
        must_change_password = true,
        activated_at = null,
        updated_at = now()
    where id = v_student_id
    returning * into v_student;

    insert into public.academy_student_activation_tokens (
        student_id, token_hash, token_hint, expires_at, created_by
    ) values (
        v_student_id,
        p_activation_token_hash,
        p_activation_token_hint,
        p_activation_expires_at,
        p_created_by
    );

    for v_index in 1..2 loop
        insert into public.academy_student_recovery_codes (
            student_id, code_hash, code_hint, created_by
        ) values (
            v_student_id,
            p_recovery_code_hashes[v_index],
            p_recovery_code_hints[v_index],
            p_created_by
        );
    end loop;

    return jsonb_set(v_result, '{student}', to_jsonb(v_student), true);
end;
$$;

comment on function public.create_academy_student_login_record(
    text, text, text, text, text, bigint, text, text, timestamptz,
    text[], text[], text, text, text, text, date, date, text
) is 'Atomically creates an academy username account with one activation token and two one-time recovery codes.';

revoke all on function public.create_academy_student_login_record(
    text, text, text, text, text, bigint, text, text, timestamptz,
    text[], text[], text, text, text, text, date, date, text
) from public, anon, authenticated;

grant execute on function public.create_academy_student_login_record(
    text, text, text, text, text, bigint, text, text, timestamptz,
    text[], text[], text, text, text, text, date, date, text
) to service_role;
